# Linked project: tguzdtwsajnnczdxjqyq
project_id = "tguzdtwsajnnczdxjqyq"

[functions.push-notify]
verify_jwt = false

[functions.create-top-up]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
