import type { MuscleKey } from '@/lib/lift/muscles';

/**
 * The official exercise catalog.
 *
 * This module is the single source of truth. The SQL seed in
 * `supabase/migrations/*_lift_slice_one.sql` is generated from it by `scripts/buildLiftSeed.mjs`,
 * so the app and the database always agree on ids and names.
 *
 * Names are written here, not scraped. Abbreviations are expanded into search aliases
 * automatically in `catalog.ts` (BB = barbell, DB = dumbbell, SM = smith), so a name only needs to
 * be spelled the way it is spoken in a gym.
 *
 * An exercise belongs to one primary muscle and any number of secondaries. Typeahead matches on
 * both, which is how Close-Grip BB Bench Press shows up whether the user picked Triceps or Chest.
 */

export type ExerciseSeed = {
  name: string;
  muscle: MuscleKey;
  secondaries: MuscleKey[];
};

function fam(muscle: MuscleKey, secondaries: MuscleKey[], names: string[]): ExerciseSeed[] {
  return names.map((name) => ({ name, muscle, secondaries }));
}

const CHEST: ExerciseSeed[] = [
  ...fam('chest', ['triceps', 'shoulders'], [
    'Flat BB Bench Press',
    'Incline BB Bench Press',
    'Low-Incline BB Bench Press',
    'Decline BB Bench Press',
    'Wide-Grip BB Bench Press',
    'Wide-Grip Incline BB Bench Press',
    'Reverse-Grip BB Bench Press',
    'Reverse-Grip Incline BB Bench Press',
    'Paused BB Bench Press',
    'BB Floor Press',
    'Spoto Press',
    'BB Board Press',
    'Bench Pin Press',
    'Larsen Press',
    'Feet-Up BB Bench Press',
    'Guillotine Press',
    'Banded BB Bench Press',
    'Chain BB Bench Press',
    'Flat SM Bench Press',
    'Incline SM Bench Press',
    'Decline SM Bench Press',
    'SM Floor Press',
  ]),
  ...fam('chest', ['triceps', 'shoulders'], [
    'Flat DB Bench Press',
    'Incline DB Bench Press',
    'Low-Incline DB Bench Press',
    'Decline DB Bench Press',
    'Neutral-Grip DB Bench Press',
    'Alternating DB Bench Press',
    'Single-Arm DB Bench Press',
    'Feet-Up DB Bench Press',
    'DB Floor Press',
    'DB Squeeze Press',
    'Incline DB Squeeze Press',
    'Twisting DB Bench Press',
  ]),
  ...fam('chest', ['triceps', 'shoulders'], [
    'Machine Chest Press',
    'Incline Machine Chest Press',
    'Decline Machine Chest Press',
    'Converging Chest Press',
    'Iso-Lateral Chest Press',
    'Plate-Loaded Chest Press',
    'Plate-Loaded Incline Chest Press',
    'Vertical Chest Press',
    'Standing Cable Chest Press',
    'Seated Cable Chest Press',
    'Single-Arm Cable Chest Press',
    'Landmine Press',
    'Half-Kneeling Landmine Press',
  ]),
  ...fam('chest', ['shoulders'], [
    'Flat DB Fly',
    'Incline DB Fly',
    'Decline DB Fly',
    'Pec Deck',
    'Machine Chest Fly',
    'Incline Machine Fly',
    'Cable Fly',
    'Incline Cable Fly',
    'Decline Cable Fly',
    'Low-to-High Cable Fly',
    'High-to-Low Cable Fly',
    'Single-Arm Cable Fly',
    'Standing Cable Crossover',
    'Kneeling Cable Crossover',
    'Bench Cable Fly',
    'Svend Press',
  ]),
  ...fam('chest', ['triceps', 'shoulders'], [
    'Chest Dip',
    'Weighted Chest Dip',
    'Assisted Chest Dip',
    'Ring Dip',
    'Push-Up',
    'Weighted Push-Up',
    'Incline Push-Up',
    'Decline Push-Up',
    'Deficit Push-Up',
    'Wide Push-Up',
    'Archer Push-Up',
    'Ring Push-Up',
    'Plyo Push-Up',
    'Banded Push-Up',
    'Pseudo Planche Push-Up',
    'Push-Up Plus',
  ]),
  ...fam('chest', ['back', 'triceps'], ['DB Pullover', 'BB Pullover']),
];

const BACK: ExerciseSeed[] = [
  ...fam('back', ['biceps', 'forearms'], [
    'Pull-Up',
    'Weighted Pull-Up',
    'Wide-Grip Pull-Up',
    'Neutral-Grip Pull-Up',
    'Chin-Up',
    'Weighted Chin-Up',
    'Commando Pull-Up',
    'Archer Pull-Up',
    'Ring Pull-Up',
    'Assisted Pull-Up Machine',
    'Band-Assisted Pull-Up',
    'Assisted Chin-Up Machine',
    'Scapular Pull-Up',
    'Rope Climb',
  ]),
  ...fam('back', ['biceps', 'forearms'], [
    'Lat Pulldown',
    'Wide-Grip Lat Pulldown',
    'Close-Grip Lat Pulldown',
    'Neutral-Grip Lat Pulldown',
    'Reverse-Grip Lat Pulldown',
    'V-Bar Lat Pulldown',
    'Single-Arm Lat Pulldown',
    'Half-Kneeling Single-Arm Lat Pulldown',
    'Kneeling Lat Pulldown',
    'Behind-the-Neck Pulldown',
    'Cross-Body Lat Pulldown',
    'Machine Pulldown',
    'Iso-Lateral Pulldown',
  ]),
  ...fam('back', ['biceps', 'traps', 'forearms'], [
    'BB Bent-Over Row',
    'Pendlay Row',
    'Underhand BB Row',
    'Wide-Grip BB Row',
    'Snatch-Grip BB Row',
    'Yates Row',
    'Meadows Row',
    'Landmine Row',
    'Single-Arm Landmine Row',
    'T-Bar Row',
    'Chest-Supported T-Bar Row',
    'Seal Row',
    'Prone Incline BB Row',
    'SM Bent-Over Row',
  ]),
  ...fam('back', ['biceps', 'traps', 'forearms'], [
    'Single-Arm DB Row',
    'Two-Arm DB Row',
    'Chest-Supported DB Row',
    'Incline DB Row',
    'DB Seal Row',
    'Dead-Stop DB Row',
    'Kroc Row',
    'Renegade Row',
    'Gorilla Row',
    'Single-Arm KB Row',
    'Batwing Row',
  ]),
  ...fam('back', ['biceps', 'traps'], [
    'Seated Cable Row',
    'Wide-Grip Seated Cable Row',
    'Close-Grip Seated Cable Row',
    'Rope Seated Cable Row',
    'Single-Arm Cable Row',
    'Standing Cable Row',
    'Machine Row',
    'Iso-Lateral Machine Row',
    'Chest-Supported Machine Row',
    'Plate-Loaded Row',
    'Low Row Machine',
    'High Row Machine',
    'Iso-Lateral High Row',
    'Iso-Lateral Low Row',
    'Sled Row',
  ]),
  ...fam('back', ['triceps', 'core'], [
    'Straight-Arm Cable Pulldown',
    'Rope Straight-Arm Pulldown',
    'Machine Pullover',
  ]),
  ...fam('back', ['hamstrings', 'glutes', 'traps', 'forearms'], [
    'Conventional Deadlift',
    'Sumo Deadlift',
    'Trap Bar Deadlift',
    'Deficit Deadlift',
    'Rack Pull',
    'Block Pull',
    'Snatch-Grip Deadlift',
    'Paused Deadlift',
    'Banded Deadlift',
  ]),
  ...fam('back', ['glutes', 'hamstrings', 'core'], [
    'Back Extension',
    '45-Degree Back Extension',
    'Weighted Back Extension',
    'Reverse Hyperextension',
    'Machine Back Extension',
    'Jefferson Curl',
    'Superman',
  ]),
  ...fam('back', ['biceps', 'core', 'forearms'], [
    'Inverted Row',
    'Feet-Elevated Inverted Row',
    'Ring Row',
    'Suspension Row',
  ]),
];

const SHOULDERS: ExerciseSeed[] = [
  ...fam('shoulders', ['triceps', 'traps', 'core'], [
    'Standing BB Overhead Press',
    'Seated BB Overhead Press',
    'Kneeling BB Overhead Press',
    'Push Press',
    'Behind-the-Neck Press',
    'Behind-the-Neck Push Press',
    'BB Z Press',
    'Overhead Pin Press',
    'Savickas Press',
    'Bradford Press',
    'Log Press',
    'Axle Overhead Press',
    'Viking Press',
  ]),
  ...fam('shoulders', ['triceps', 'traps'], [
    'Seated DB Shoulder Press',
    'Standing DB Shoulder Press',
    'Incline DB Shoulder Press',
    'Neutral-Grip DB Shoulder Press',
    'Single-Arm DB Shoulder Press',
    'Half-Kneeling DB Overhead Press',
    'Single-Arm DB Push Press',
    'Arnold Press',
    'Seated Arnold Press',
    'DB Z Press',
    'Circus DB Press',
    'KB Overhead Press',
    'Bottoms-Up KB Press',
    'Double KB Press',
    'Tall-Kneeling KB Press',
  ]),
  ...fam('shoulders', ['triceps', 'traps'], [
    'SM Shoulder Press',
    'Machine Shoulder Press',
    'Iso-Lateral Shoulder Press',
    'Plate-Loaded Shoulder Press',
    'Standing Cable Overhead Press',
    'Half-Kneeling Cable Press',
    'Landmine Shoulder Press',
    'Single-Arm Landmine Press',
  ]),
  ...fam('shoulders', ['triceps', 'core'], ['Handstand Push-Up', 'Pike Push-Up']),
  ...fam('shoulders', ['traps'], [
    'DB Lateral Raise',
    'Seated DB Lateral Raise',
    'Incline DB Lateral Raise',
    'Partial DB Lateral Raise',
    'Dead-Stop DB Lateral Raise',
    'Cable Lateral Raise',
    'Single-Arm Cable Lateral Raise',
    'Behind-the-Back Cable Lateral Raise',
    'Leaning Cable Lateral Raise',
    'Machine Lateral Raise',
    'Seated Machine Lateral Raise',
    'Banded Lateral Raise',
    'Landmine Lateral Raise',
    'Lu Raise',
    'DB Scaption',
    'DB 6-Way Raise',
    'Bus Driver',
  ]),
  ...fam('shoulders', ['chest'], [
    'DB Front Raise',
    'BB Front Raise',
    'Plate Front Raise',
    'Cable Front Raise',
    'Rope Front Raise',
    'Incline DB Front Raise',
  ]),
  ...fam('shoulders', ['traps', 'back'], [
    'DB Rear Delt Fly',
    'Seated DB Rear Delt Fly',
    'Chest-Supported Rear Delt Fly',
    'Reverse Pec Deck',
    'Cable Rear Delt Fly',
    'Single-Arm Cable Rear Delt Fly',
    'Cable Crossover Rear Delt Fly',
    'Cable Rear Delt Row',
    'Wide-Grip BB High Row',
    'Cable Face Pull',
    'Band Face Pull',
    'Band Pull-Apart',
    'Prone Y Raise',
    'Prone T Raise',
    'Prone W Raise',
    'Cable Y-Raise',
  ]),
  ...fam('shoulders', ['traps', 'core'], [
    'Cable External Rotation',
    'DB External Rotation',
    'Band External Rotation',
    'Cable Internal Rotation',
    'Cuban Press',
    'KB Halo',
    'Wall Slide',
    'Band Shoulder Dislocate',
    'Overhead Carry',
    'Waiter Walk',
    'Bottoms-Up KB Carry',
  ]),
];

const TRAPS: ExerciseSeed[] = [
  ...fam('traps', ['forearms', 'shoulders'], [
    'BB Shrug',
    'Behind-the-Back BB Shrug',
    'DB Shrug',
    'Seated DB Shrug',
    'Incline DB Shrug',
    'SM Shrug',
    'Trap Bar Shrug',
    'Cable Shrug',
    'Rope Cable Shrug',
    'Machine Shrug',
    'Plate-Loaded Shrug',
    'Snatch-Grip Shrug',
    'Overhead Shrug',
    'Paused BB Shrug',
    'Kirk Shrug',
    'Band Shrug',
    'Seated Cable Shrug',
    'Chest-Supported Shrug',
    'Prone Incline Shrug',
    'Bent-Over Shrug',
    'Landmine Shrug',
    'Rack Pull Shrug',
  ]),
  ...fam('traps', ['shoulders', 'biceps'], [
    'BB Upright Row',
    'Wide-Grip BB Upright Row',
    'DB Upright Row',
    'Cable Upright Row',
    'Rope Upright Row',
    'SM Upright Row',
    'KB Upright Row',
    'High Pull',
    'BB High Pull',
    'DB High Pull',
    'Snatch-Grip High Pull',
  ]),
  ...fam('traps', ['shoulders', 'back'], [
    'Y-Raise',
    'Incline Y-Raise',
    'Prone Trap Raise',
    'Cable Trap-3 Raise',
    'Scapular Shrug',
    'Powell Raise',
  ]),
  ...fam('traps', ['forearms', 'core'], [
    "Farmer's Carry",
    'Trap Bar Carry',
    'Suitcase Carry',
    'Heavy DB Hold',
    'Zercher Carry',
    'Yoke Walk',
  ]),
];

const BICEPS: ExerciseSeed[] = [
  ...fam('biceps', ['forearms'], [
    'BB Curl',
    'EZ-Bar Curl',
    'Wide-Grip BB Curl',
    'Close-Grip BB Curl',
    'Cheat Curl',
    'Strict Curl',
    'Reverse BB Curl',
    'Drag Curl',
    '21s',
    'BB Preacher Curl',
    'EZ-Bar Preacher Curl',
    'SM Drag Curl',
  ]),
  ...fam('biceps', ['forearms'], [
    'DB Curl',
    'Alternating DB Curl',
    'Seated DB Curl',
    'Standing DB Curl',
    'Incline DB Curl',
    'Spider Curl',
    'DB Preacher Curl',
    'Concentration Curl',
    'Hammer Curl',
    'Incline Hammer Curl',
    'Cross-Body Hammer Curl',
    'Zottman Curl',
    'Waiter Curl',
    'DB Reverse Curl',
    'Prone Incline DB Curl',
    'Kneeling DB Curl',
  ]),
  ...fam('biceps', ['forearms'], [
    'Cable Curl',
    'Rope Hammer Curl',
    'Bayesian Cable Curl',
    'High Cable Curl',
    'Single-Arm Cable Curl',
    'Cable Preacher Curl',
    'Cable Reverse Curl',
    'EZ-Bar Cable Curl',
    'Overhead Cable Curl',
    'Lying Cable Curl',
  ]),
  ...fam('biceps', ['forearms', 'back'], [
    'Machine Preacher Curl',
    'Machine Bicep Curl',
    'Plate-Loaded Preacher Curl',
    'Band Curl',
    'Chin-Up Hold',
    'Bodyweight Bicep Curl',
    'Ring Curl',
    'KB Curl',
    'Fat-Grip DB Curl',
    'Static Hold Curl',
  ]),
];

const TRICEPS: ExerciseSeed[] = [
  ...fam('triceps', ['chest', 'shoulders'], [
    'Close-Grip BB Bench Press',
    'Close-Grip Incline BB Bench Press',
    'Close-Grip SM Bench Press',
    'Close-Grip DB Press',
    'Bench Dip',
    'Weighted Bench Dip',
    'Triceps Dip',
    'Machine Triceps Dip',
    'Diamond Push-Up',
    'Sphinx Push-Up',
    'JM Press',
    'Floor Skull Crusher',
  ]),
  ...fam('triceps', ['shoulders'], [
    'EZ-Bar Skull Crusher',
    'BB Skull Crusher',
    'DB Skull Crusher',
    'Incline Skull Crusher',
    'Decline Skull Crusher',
    'Cable Skull Crusher',
    'Rope Skull Crusher',
    'Overhead BB Extension',
    'Overhead DB Extension',
    'Single-Arm Overhead DB Extension',
    'Seated Overhead DB Extension',
    'Overhead Cable Extension',
    'Rope Overhead Cable Extension',
    'Single-Arm Overhead Cable Extension',
    'Kneeling Overhead Cable Extension',
    'Cross-Body Cable Extension',
  ]),
  ...fam('triceps', [], [
    'Cable Pushdown',
    'Rope Pushdown',
    'Straight-Bar Pushdown',
    'V-Bar Pushdown',
    'Reverse-Grip Pushdown',
    'Single-Arm Cable Pushdown',
    'Machine Triceps Extension',
    'Plate-Loaded Triceps Extension',
    'Band Pushdown',
    'DB Triceps Kickback',
    'Bent-Over DB Kickback',
    'Cable Triceps Kickback',
    'Tate Press',
    'DB Triceps Extension',
    'Katana Extension',
  ]),
  ...fam('triceps', ['chest', 'core'], [
    'Ring Triceps Extension',
    'Bodyweight Skull Crusher',
    'Suspension Triceps Extension',
    'Pin Close-Grip Press',
    'Board Close-Grip Press',
    'California Press',
    'Rolling DB Extension',
  ]),
];

const FOREARMS: ExerciseSeed[] = [
  ...fam('forearms', [], [
    'BB Wrist Curl',
    'Seated BB Wrist Curl',
    'DB Wrist Curl',
    'Behind-the-Back BB Wrist Curl',
    'Cable Wrist Curl',
    'BB Reverse Wrist Curl',
    'DB Reverse Wrist Curl',
    'Cable Reverse Wrist Curl',
    'Machine Wrist Curl',
    'Band Wrist Curl',
  ]),
  ...fam('forearms', ['biceps'], [
    'Reverse Curl',
    'EZ-Bar Reverse Curl',
    'Cable Rope Reverse Curl',
    'Hammer Curl (Forearm Focus)',
    'Zottman Reverse Curl',
    'Pronated DB Curl',
    'Fat-Grip Hold',
  ]),
  ...fam('forearms', ['traps'], [
    'Dead Hang',
    'Weighted Dead Hang',
    'Towel Hang',
    'Plate Pinch',
    'Plate Pinch Carry',
    'Farmer Hold',
    'Captains of Crush Grip',
    'Hand Gripper',
    'Fat-Grip Farmer Walk',
    'Wrist Roller',
    'Reverse Wrist Roller',
    'Sledgehammer Lever',
    'Radial Deviation',
    'Ulnar Deviation',
    'Rice Bucket Dig',
    'Rubber Band Extension',
    'Finger Extension',
    'Barbell Holds',
    'Axle Bar Hold',
    'Thick Bar Deadlift Hold',
  ]),
  ...fam('forearms', ['biceps', 'core'], [
    'Pronation with Hammer',
    'Supination with Hammer',
    'Cable Pronation',
    'Cable Supination',
  ]),
];

const QUADS: ExerciseSeed[] = [
  ...fam('quads', ['glutes', 'hamstrings', 'core'], [
    'Back Squat',
    'High-Bar Back Squat',
    'Low-Bar Back Squat',
    'Front Squat',
    'Paused Back Squat',
    'Paused Front Squat',
    'Box Squat',
    'Tempo Back Squat',
    'Pin Squat',
    'Anderson Squat',
    'Safety Bar Squat',
    'Zercher Squat',
    'Overhead Squat',
    'Banded Back Squat',
    'Chain Back Squat',
    'Wide-Stance Back Squat',
    'Narrow-Stance Back Squat',
    'Heels-Elevated Back Squat',
    'SM Squat',
    'SM Front Squat',
    'SM Heels-Elevated Squat',
    'Hack Squat',
    'Machine Hack Squat',
    'Reverse Hack Squat',
    'V-Squat',
    'Pendulum Squat',
    'Belt Squat',
    'Landmine Squat',
  ]),
  ...fam('quads', ['glutes', 'core'], [
    'Goblet Squat',
    'DB Squat',
    'KB Goblet Squat',
    'Double KB Front Squat',
    'DB Front Squat',
    'Bodyweight Squat',
    'Sissy Squat',
    'Machine Sissy Squat',
    'Cyclist Squat',
    'Wall Sit',
    'Jump Squat',
    'Box Jump',
    'Pause Goblet Squat',
    'Bulgarian Split Squat',
    'DB Bulgarian Split Squat',
    'BB Bulgarian Split Squat',
    'SM Bulgarian Split Squat',
    'Split Squat',
    'DB Split Squat',
    'Front-Foot-Elevated Split Squat',
    'Deficit Split Squat',
  ]),
  ...fam('quads', ['glutes', 'hamstrings'], [
    'Leg Press',
    'Narrow-Stance Leg Press',
    'Single-Leg Leg Press',
    'Horizontal Leg Press',
    '45-Degree Leg Press',
    'Vertical Leg Press',
    'Leg Extension',
    'Single-Leg Extension',
    'Paused Leg Extension',
    'Banded Leg Extension',
    'Machine Squat',
    'Smith Leg Press',
  ]),
  ...fam('quads', ['glutes', 'core'], [
    'Walking Lunge',
    'DB Walking Lunge',
    'BB Walking Lunge',
    'Reverse Lunge',
    'DB Reverse Lunge',
    'BB Reverse Lunge',
    'Forward Lunge',
    'Deficit Reverse Lunge',
    'Curtsy Lunge',
    'Lateral Lunge',
    'Step-Up',
    'DB Step-Up',
    'BB Step-Up',
    'Lateral Step-Up',
    'Deficit Step-Up',
    'Pistol Squat',
    'Assisted Pistol Squat',
    'Skater Squat',
    'Cossack Squat',
    'Sled Push',
    'Sled Drag',
    'Nordic Reverse Curl',
    'Spanish Squat',
    'Terminal Knee Extension',
    'Petersen Step-Up',
  ]),
];

const HAMSTRINGS: ExerciseSeed[] = [
  ...fam('hamstrings', ['glutes', 'back'], [
    'Romanian Deadlift',
    'DB Romanian Deadlift',
    'Single-Leg Romanian Deadlift',
    'DB Single-Leg Romanian Deadlift',
    'Stiff-Leg Deadlift',
    'Deficit Romanian Deadlift',
    'SM Romanian Deadlift',
    'Trap Bar Romanian Deadlift',
    'KB Romanian Deadlift',
    'Snatch-Grip Romanian Deadlift',
    'Good Morning',
    'Seated Good Morning',
    'SM Good Morning',
    'Safety Bar Good Morning',
    'Banded Good Morning',
    'Jefferson Deadlift',
  ]),
  ...fam('hamstrings', ['calves', 'glutes'], [
    'Lying Leg Curl',
    'Seated Leg Curl',
    'Standing Leg Curl',
    'Single-Leg Lying Curl',
    'Single-Leg Seated Curl',
    'Cable Leg Curl',
    'Banded Leg Curl',
    'Stability Ball Leg Curl',
    'Slider Leg Curl',
    'Nordic Hamstring Curl',
    'Assisted Nordic Curl',
    'Razor Curl',
    'Glute-Ham Raise',
    'Machine Glute-Ham Raise',
    'Reverse Nordic',
  ]),
  ...fam('hamstrings', ['glutes', 'core'], [
    'Cable Pull-Through',
    'Band Pull-Through',
    'KB Swing',
    'American KB Swing',
    'Single-Arm KB Swing',
    'Hip Hinge Drill',
    '45-Degree Hip Extension',
    'Single-Leg Back Extension',
    'Sled Backward Drag',
    'Hamstring Slider Bridge',
    'Single-Leg Hamstring Bridge',
    'Long-Lever Bridge',
    'Kettlebell Deadlift',
    'Stiff-Leg DB Deadlift',
    'Hyperextension Hold',
  ]),
];

const GLUTES: ExerciseSeed[] = [
  ...fam('glutes', ['hamstrings', 'quads'], [
    'BB Hip Thrust',
    'DB Hip Thrust',
    'SM Hip Thrust',
    'Machine Hip Thrust',
    'Single-Leg Hip Thrust',
    'Banded Hip Thrust',
    'Paused Hip Thrust',
    'Feet-Elevated Hip Thrust',
    'B-Stance Hip Thrust',
    'Glute Bridge',
    'BB Glute Bridge',
    'Single-Leg Glute Bridge',
    'Frog Pump',
    'Frog Hip Thrust',
    'Hip Thrust Machine (Plate-Loaded)',
  ]),
  ...fam('glutes', ['hamstrings', 'core'], [
    'Cable Glute Kickback',
    'Machine Glute Kickback',
    'Standing Glute Kickback',
    'Quadruped Hip Extension',
    'Donkey Kick',
    'Fire Hydrant',
    'Banded Kickback',
    'Cable Pull-Through (Glute Focus)',
    'Reverse Hyper (Glute Focus)',
    'Kneeling Hip Thrust',
    'Kneeling Banded Hip Thrust',
    'Single-Leg Hip Extension',
  ]),
  ...fam('glutes', ['quads', 'core'], [
    'Hip Abduction Machine',
    'Seated Hip Abduction',
    'Standing Cable Abduction',
    'Banded Lateral Walk',
    'Monster Walk',
    'Clamshell',
    'Side-Lying Hip Raise',
    'Copenhagen Plank',
    'Hip Adduction Machine',
    'Cable Hip Adduction',
    'Sumo Squat',
    'DB Sumo Squat',
    'KB Sumo Deadlift',
    'Curtsy Squat',
    'Step-Up (Glute Focus)',
    'Deficit Curtsy Lunge',
    'Glute-Focused Back Extension',
    'Single-Leg Squat to Box',
  ]),
];

const CALVES: ExerciseSeed[] = [
  ...fam('calves', [], [
    'Standing Calf Raise',
    'Machine Standing Calf Raise',
    'SM Calf Raise',
    'BB Standing Calf Raise',
    'DB Standing Calf Raise',
    'Single-Leg Standing Calf Raise',
    'Bodyweight Calf Raise',
    'Deficit Calf Raise',
    'Paused Calf Raise',
    'Seated Calf Raise',
    'Machine Seated Calf Raise',
    'DB Seated Calf Raise',
    'Plate Seated Calf Raise',
    'Leg Press Calf Raise',
    'Hack Squat Calf Raise',
    'Donkey Calf Raise',
    'Machine Donkey Calf Raise',
    'Single-Leg Leg Press Calf Raise',
    'Banded Calf Raise',
    'Cable Calf Raise',
    'BB Seated Calf Raise',
    'SM Seated Calf Raise',
    'Single-Leg Seated Calf Raise',
    'Bent-Knee Calf Raise',
    'Straight-Leg Calf Raise',
    'Explosive Calf Raise',
  ]),
  ...fam('calves', ['core'], [
    'Tibialis Raise',
    'Weighted Tibialis Raise',
    'Banded Tibialis Raise',
    'Toe Walk',
    'Heel Walk',
    'Farmer Walk on Toes',
    'Jump Rope',
    'Pogo Hop',
    'Calf Jump',
    'Ankle Bounce',
    'Seated Tibialis Raise',
    'Soleus Push-Up',
    'Eccentric Calf Drop',
    'Sled Toe Push',
    'Stair Calf Raise',
  ]),
];

const CORE: ExerciseSeed[] = [
  ...fam('core', [], [
    'Plank',
    'Weighted Plank',
    'Long-Lever Plank',
    'Side Plank',
    'Weighted Side Plank',
    'RKC Plank',
    'Body Saw',
    'Stir the Pot',
    'Ab Wheel Rollout',
    'Kneeling Ab Wheel Rollout',
    'Standing Ab Wheel Rollout',
    'Barbell Rollout',
    'Suspension Fallout',
    'Hollow Body Hold',
    'Hollow Rock',
    'Dead Bug',
    'Weighted Dead Bug',
    'Bird Dog',
  ]),
  ...fam('core', ['hamstrings'], [
    'Hanging Knee Raise',
    'Hanging Leg Raise',
    'Weighted Hanging Leg Raise',
    'Toes-to-Bar',
    'Captain Chair Knee Raise',
    'Captain Chair Leg Raise',
    'Lying Leg Raise',
    'Lying Knee Raise',
    'Decline Leg Raise',
    'Reverse Crunch',
    'Weighted Reverse Crunch',
    'Dragon Flag',
    'V-Up',
    'Tuck-Up',
    'Jackknife',
  ]),
  ...fam('core', [], [
    'Crunch',
    'Weighted Crunch',
    'Cable Crunch',
    'Rope Cable Crunch',
    'Machine Crunch',
    'Decline Crunch',
    'Sit-Up',
    'Weighted Sit-Up',
    'Decline Sit-Up',
    'GHD Sit-Up',
    'Bicycle Crunch',
    'Toe Touch',
    'Flutter Kick',
    'Scissor Kick',
  ]),
  ...fam('core', ['glutes', 'shoulders'], [
    'Pallof Press',
    'Half-Kneeling Pallof Press',
    'Cable Woodchop',
    'Low-to-High Woodchop',
    'High-to-Low Woodchop',
    'Russian Twist',
    'Weighted Russian Twist',
    'Landmine Twist',
    'Landmine Rainbow',
    'Suitcase Hold',
    'Side Bend',
    'Cable Side Bend',
    'Windmill',
    'Turkish Get-Up',
    'Bear Crawl',
    'Hanging Windshield Wiper',
    'Dead Bug Pallof',
  ]),
];

const OLYMPIC: ExerciseSeed[] = [
  ...fam('olympic', ['quads', 'traps', 'shoulders', 'back'], [
    'Snatch',
    'Power Snatch',
    'Hang Snatch',
    'Hang Power Snatch',
    'Block Snatch',
    'Muscle Snatch',
    'Snatch Pull',
    'High Hang Snatch',
    'Snatch Balance',
    'Overhead Squat (Snatch)',
    'Snatch Deadlift',
    'DB Snatch',
    'Single-Arm KB Snatch',
  ]),
  ...fam('olympic', ['quads', 'traps', 'shoulders'], [
    'Clean',
    'Power Clean',
    'Hang Clean',
    'Hang Power Clean',
    'Block Clean',
    'Muscle Clean',
    'Clean Pull',
    'High Hang Clean',
    'Clean Deadlift',
    'DB Clean',
    'KB Clean',
    'Clean and Jerk',
    'Clean and Press',
    'Squat Clean',
  ]),
  ...fam('olympic', ['shoulders', 'triceps', 'quads'], [
    'Split Jerk',
    'Power Jerk',
    'Push Jerk',
    'Jerk from Blocks',
    'Behind-the-Neck Jerk',
    'Jerk Balance',
    'Jerk Dip',
    'Thruster',
    'DB Thruster',
    'KB Thruster',
    'Wall Ball',
  ]),
  ...fam('olympic', ['core', 'quads', 'back'], [
    'Burpee',
    'Burpee Box Jump',
    'Devil Press',
    'Man Maker',
    'Battle Rope Wave',
    'Sledgehammer Swing',
    'Tire Flip',
    'Atlas Stone Lift',
    'Sandbag Clean',
    'Sandbag Carry',
    'Keg Toss',
    'Medicine Ball Slam',
    'Rotational Med Ball Throw',
    'Broad Jump',
    'Assault Bike Sprint',
    'Rower Sprint',
    'Ski Erg Sprint',
  ]),
];

export const OFFICIAL_EXERCISE_SEEDS: readonly ExerciseSeed[] = [
  ...CHEST,
  ...BACK,
  ...SHOULDERS,
  ...TRAPS,
  ...BICEPS,
  ...TRICEPS,
  ...FOREARMS,
  ...QUADS,
  ...HAMSTRINGS,
  ...GLUTES,
  ...CALVES,
  ...CORE,
  ...OLYMPIC,
];
