export const COPY_TONES = ['gentle', 'neutral', 'honest'] as const;

export type CopyTone = (typeof COPY_TONES)[number];

const STRINGS = {
  'bfp.sliderHint': {
    gentle: 'Adjust until this matches how you look right now — or enter your actual body-fat %.',
    neutral: 'Slide to your current body type, or type your actual body-fat %.',
    honest: 'Set current body fat, not a goal. Slide to match today, or enter the real %.',
  },
  'bfp.enterExact': 'Enter exact %',
  'bfp.exactLabel': 'Exact body fat %',
  'training.lastDoneHint': 'When is the last time you participated in these activities?',
  'training.aims': 'Aims',
  'profile.update': 'Update profile',
  'profile.saved': 'Saved.',
  'profile.toneLabel': 'How should Bob talk to you?',
  'profile.toneGentle': 'Gentle',
  'profile.toneNeutral': 'Neutral',
  'profile.toneHonest': 'Honest',
  'profile.encouragementLabel': 'How should Bob nudge you?',
  'profile.encouragementHelp': 'Alerts from Bob when you check in, miss, or come back. Separate from how the app talks to you.',
  'error.uploadPhoto': 'Couldn’t upload photo. Try again.',
  'error.preferenceSave': 'Couldn’t save that preference. You can set it later.',
  'error.notEnoughPeople': 'Not enough people joined.',
  'post.deleteConfirm': 'Delete?',
  'post.delete': 'Delete',
  'post.edit': 'Edit',
  'post.edited': 'Edited',
  'post.editHistory': 'Edit history',
  'post.hiddenByAuthor': 'Hidden by author',
  'post.hidden': 'Hidden',
  'post.unhide': 'Unhide',
  'post.hidePhoto': 'Hide this photo?',
  'post.hidePhotoBody': 'Others will see a blur. The file stays on your check-in.',
  'post.hideFailed': 'Couldn’t hide that photo.',
  'post.saveFailed': 'Couldn’t save.',
  'post.noChanges': 'No changes.',
  'post.discard': 'Discard',
  'post.discardConfirm': 'Discard this post?',
  'post.clear': 'Clear',
  'post.savePhotoFirst': 'Save this photo first.',
  'post.replaceFirst': 'Replace this photo first.',
  'post.replaceFirstBody': 'A required proof needs a visible photo. Hide it after you add a new one.',
  'error.deletePost': 'Couldn’t delete.',
  'account.passwordHint': 'Use upper and lower case, a number, and a symbol.',
  'account.passwordUpdated': 'Password updated.',
  'error.passwordWeak': 'Needs a lowercase, uppercase, number, and symbol.',
  'error.passwordSame': 'Pick a different password.',
  'error.passwordSession': 'Sign out and sign in again, then change your password.',
  'error.passwordMin': 'Use at least 8 characters.',
  'error.passwordUpdate': 'Couldn’t update password. Try again.',
  'error.passwordMismatch': 'Those passwords don’t match.',
  'auth.forgotPassword': 'Forgot password?',
  'auth.resetEmailSent': 'Check your inbox for a reset link.',
  'auth.setPasswordTitle': 'Set new password',
  'auth.setPasswordBody': 'Pick a new password to finish resetting.',
  'auth.resetLinkExpired': 'This reset link is invalid or expired. Request a new one.',
  'auth.sendResetLink': 'Send reset link',
  'auth.welcome': {
    gentle: 'Welcome back. I saved you a spot.',
    neutral: 'Welcome back.',
    honest: 'You’re late. Sign in.',
  },
  'auth.subtitle': {
    gentle: 'I’m Bob. We can go slow. We still go.',
    neutral: 'I’m Bob. Sign in and we’ll get to work.',
    honest: 'I’m Bob. Effort is the only door. Sign in.',
  },
  'auth.signingIn': {
    gentle: 'Almost in. Don’t wander off.',
    neutral: 'Signing you in.',
    honest: 'Waiting on you, not the internet.',
  },
  'auth.createAccount': 'Create account',
  'auth.signIn': 'Sign in',
  'auth.checkInboxThenSignIn': 'Check your inbox, then sign in here.',
  'auth.emailConfirmed': 'Email confirmed. Open blOb.',
  'auth.openBlob': 'Open blOb',
  'auth.continueInBrowser': 'Continue in browser',
  'auth.confirmLinkBad': 'This confirm link is missing or expired. Sign in.',
  'auth.waitRetry': 'Please wait a few seconds and try again.',
  'auth.emailExists': 'That email already has an account. Sign in.',
  'auth.network': 'Couldn’t reach the server. Try again.',
  'auth.newHere': 'New here?',
  'home.header': 'Home',
  'home.loading': {
    gentle: 'Checking who showed up for you.',
    neutral: 'Checking who showed up.',
    honest: 'If this takes a while, it is not because you stretched.',
  },
  'home.error': {
    gentle: 'Home didn’t load. Try again when you’re ready.',
    neutral: 'Home didn’t load.',
    honest: 'Home didn’t load. Tapping again is allowed.',
  },
  'home.empty': {
    gentle: 'Nobody you know has posted. You can go first. I will watch.',
    neutral: 'Nobody you know has posted.',
    honest: 'Empty on purpose until someone posts. That can be you.',
  },
  'home.composer': {
    gentle: 'What did you do? Even a little counts.',
    neutral: 'What did you do?',
    honest: 'What did you actually do?',
  },
  'lobby.subtitle': 'Find a challenge. Pay the entry fee. Prove the work.',
  'lobby.loading': {
    gentle: 'Looking for Challenges. Stay here.',
    neutral: 'Looking for Challenges.',
    honest: 'Looking for Challenges. They will not find you first.',
  },
  'lobby.empty': {
    gentle: 'Nothing open yet. You could start one. I’ll stand next to it.',
    neutral: 'Nothing open yet. You could start one.',
    honest: 'Nothing open. Create one or go home. Those are the options.',
  },
  'lobby.unreachable': 'Couldn’t load the Lobby.',
  'lobby.railHosting': 'Hosting',
  'lobby.railActive': 'Active',
  'lobby.railOfficial': 'Official',
  'lobby.railFriends': 'Friends',
  'feed.railActive': 'Active',
  'feed.featuredChallenge': 'Featured Challenge',
  'feed.peopleYouMayKnow': 'People you may know',
  'feed.youreIn': 'You’re in',
  'feed.notJoined': 'Not joined',
  'feed.openChallenge': 'Open',
  'feed.logToday': 'Check in today',
  'lobby.friendsHosting': '{name} is hosting',
  'lobby.friendsJoined': '{name} joined',
  'create.friendsOfFriends': 'Visible to friends of friends',
  'geo.unavailable': 'Sorry, this Challenge isn’t available in your State.',
  'challenge.privateWallTitle': 'Private challenge',
  'challenge.privateWall': 'This is a private challenge. Only competitors can open it.',
  'feed.checkedIn': 'Checked in ·',
  'friends.loading': {
    gentle: 'Finding your people.',
    neutral: 'Finding your people.',
    honest: 'Looking up who actually knows you.',
  },
  'friends.empty': {
    gentle: 'No friends yet. That’s a beginning, not a verdict.',
    neutral: 'No friends yet.',
    honest: 'No friends yet. Search. Send a request. Waiting is not a strategy.',
  },
  'friends.noneMatch': {
    gentle: 'Nobody matches that. Try a different name.',
    neutral: 'Nobody matches that.',
    honest: 'Nobody matches that. Check the spelling before you invent a person.',
  },
  'friends.searchPlaceholder': 'Name, @username, email, or phone',
  'alerts.empty': {
    gentle: 'Nothing new. I’ll tap you when there is.',
    neutral: 'Nothing new.',
    honest: 'Nothing new. That is not the same as done.',
  },
  'alerts.loading': 'Checking your inbox.',
  'alerts.error': 'Couldn’t load notifications.',
  'messages.empty': {
    gentle: 'No chats yet. Say something kind. Or useful. Both is better.',
    neutral: 'No chats yet.',
    honest: 'No chats. Messages do not send themselves.',
  },
  'messages.error': 'Couldn’t load messages.',
  'messages.loading': 'Opening your inbox.',
  'messages.blocked': 'You can’t message this person.',
  'messages.openFailed': 'Couldn’t open this chat. Try again.',
  'messages.newHint': 'Search anyone by name or username. Groups stay with friends.',
  'messages.searchPlaceholder': 'Search by name or username',
  'messages.blockedState': 'Blocked',
  'profile.loading': {
    gentle: 'Looking you up.',
    neutral: 'Looking you up.',
    honest: 'Loading the facts. Not the story you tell yourself.',
  },
  'profile.error': 'Couldn’t load your profile.',
  'profile.notFound': 'Couldn’t load that profile.',
  'notFound.title': {
    gentle: 'That door doesn’t go anywhere. Let’s go back.',
    neutral: 'That door doesn’t go anywhere.',
    honest: 'That door doesn’t go anywhere. Stop knocking.',
  },
  'challenge.logClosed': 'Check-in is closed.',
  'challenge.notStarted': 'This challenge hasn’t started yet.',
  'challenge.eliminated': 'You have been eliminated.',
  'challenge.cancel': 'Cancel challenge',
  'challenge.delete': 'Delete',
  'challenge.cancelKeep': 'Keep',
  'challenge.leave': 'Leave',
  'challenge.leaveConfirm': 'Leave this Skill Tournament? Your entry fee comes back in full.',
  'challenge.leaveKeep': 'Stay',
  'error.leaveChallenge': 'Couldn’t leave. Try again.',
  'challenge.startMovedTitle': 'Start moved',
  'challenge.keepDays': 'Keep {n} days',
  'challenge.shortenDay': 'Shorten by 1 day',
  'challenge.startMovedLater': 'Not now',
  'challenge.pickStart': 'Pick a start date',
  'error.startUpdate': 'Couldn’t update the start.',
  'error.cancelChallenge': 'Couldn’t cancel. Try again.',
  'error.composerUpload': 'Couldn’t upload that. The post wasn’t sent.',
  'error.usePhotoOrVideo': 'Use a photo or video.',
  'challenge.startTomorrow': 'Start tomorrow',
  'challenge.editChallenge': 'Edit challenge',
  'challenge.editDetails': 'Edit details',
  'create.rulesLabel': 'Rules',
  'create.rulesPlaceholder': 'How this challenge works. Separate paragraphs with a blank line.',
  'create.sponsorLabel': 'Sponsor',
  'create.sponsorPlaceholder': 'Optional',
  'error.saveDetails': 'Couldn’t save those details.',
  'challenge.waitingToStart': 'Waiting to start.',
  'create.minToStart': 'Min to start',
  'create.minToStartHint': 'Includes you. If fewer people have joined at start, it waits and the start moves to the next day.',
  'create.editTitle': 'Edit Challenge',
  'create.save': 'Save',
  'challenge.cancelConfirmCoins': 'Cancel this challenge? Anyone who paid gets their coins back.',
  'challenge.cancelConfirmFree': 'Cancel this challenge? It will disappear from Lobby and the feed.',
  'challenge.cancelled': 'This challenge was cancelled.',
  'challenge.cancelledToast': 'Challenge cancelled.',
  'challenge.notFound': 'Challenge not found.',
  'challenge.unavailable': 'This challenge isn’t available.',
  'challenge.private': 'This challenge is private.',
  'challenge.joinFirst': 'Join first.',
  'create.screenTitle': 'New Skill Tournament',
  'create.currency': 'Currency',
  'create.coins': 'Coins',
  'create.bucks': '$',
  'create.youFundPrize': 'You fund the prize.',
  'create.hostPrize': 'Host contribution',
  'create.totalPrizePool': 'Prize',
  'create.realMoneyFund':
    'The entry fee helps cover technology and tournament management. The prize is entry fees plus any host funds.',
  'create.hostContributionHelp': 'Optional. You can add more from your balance any time before settlement.',
  'create.buyIn': 'Entry fee',
  'create.freeEntry': 'FREE Entry',
  'create.free': 'FREE',
  'create.guaranteePrize': 'Guaranteed Prize',
  'create.guaranteePrizeHelp': 'Optional floor on Official cards. Off by default for Private Corporate.',
  'create.type': 'Type',
  'create.titleLabel': 'Title',
  'create.titlePlaceholder': 'Morning miles',
  'create.descriptionLabel': 'Description',
  'create.descriptionPlaceholder': 'Optional',
  'create.photoLabel': 'Challenge photo',
  'create.photoHelper': 'Shown on Lobby and when people share this challenge.',
  'create.photoAdd': 'Add photo',
  'create.photoCamera': 'Camera',
  'create.photoGallery': 'Gallery',
  'create.photoReplace': 'Replace',
  'create.photoRemove': 'Remove',
  'create.start': 'Start',
  'create.duration': 'Duration',
  'create.days': 'Days',
  'create.taskLabel': 'Task',
  'create.taskPlaceholder': 'Run 1 mile',
  'create.frequency': 'Frequency',
  'create.checkins': 'Check-ins',
  'create.proof': 'Proof',
  'create.proofs': 'Proofs',
  'create.addProof': 'Add proof',
  'create.proofPreset': 'Before · After · heart rate',
  'create.proofsHelper': "Say the action. 'Photo' is not enough.",
  'create.proofFallback': 'Post a photo of the work.',
  'create.proofPhoto': 'Photo',
  'create.proofVideo': 'Video',
  'create.proofCheckin': 'Note',
  'create.proofHonor': 'Honor',
  'create.proofHr': 'Heart rate',
  'create.proofDistance': 'Distance',
  'create.proofLocation': 'Location',
  'create.locationLabel': 'Place name',
  'create.locationPlaceholder': 'Gym, store, or home',
  'create.locationRadius': 'Radius',
  'create.locationSearch': 'Search for a place',
  'checkin.imHere': 'I’m here',
  'checkin.locationNeedPhone': 'Open the blOb app on your phone to check in at {place}.',
  'checkin.locationTooFar': 'You don’t look close enough to {place}. Move closer and try again.',
  'checkin.locationPermission': 'Turn on Location in Settings.',
  'create.howYouWin': 'How you win',
  'create.needScoreboard': 'Need a scoreboard? Use Advanced.',
  'create.pointsInAdvanced': 'Points boards are in Advanced.',
  'create.cumulative': 'Cumulative',
  'create.cumulativeTarget': 'Target',
  'create.cumulativeWindow': 'Window',
  'create.windowChallenge': 'This challenge',
  'create.windowWeek': 'Each week',
  'create.distanceUnitMi': 'mi',
  'create.distanceUnitKm': 'km',
  'create.healthOnIos': 'Attach a workout from Apple Health in the iOS app.',
  'create.visibility': 'Visibility',
  'create.public': 'Public',
  'create.friends': 'Friends',
  'create.invite': 'Invite',
  'create.private': 'Private',
  'create.privateHelp': 'Invite-only. Not listed in public discovery.',
  'create.privateCorporate': 'Private Corporate',
  'create.privateCorporateHelp':
    'Only participants can see activity. Nothing leaves the Lobby. Required for most company-sponsored contests.',
  'create.privacyLocked':
    'Privacy is locked. After someone joins, you cannot turn off or downgrade this setting.',
  'create.submit': 'Create',
  'create.advanced': 'Advanced',
  'create.simple': 'Simple',
  'create.setHostPrize': 'Set a host prize.',
  'create.needTitle': 'Give it a title.',
  'create.needStart': 'Pick a start.',
  'create.startFuture': 'Start has to be in the future.',
  'create.needDuration': 'Duration has to be at least 1 day.',
  'create.needTask': 'Add a task.',
  'create.needExtraTask': 'Name each extra task, or remove it.',
  'create.addTask': 'Add another task',
  'create.addTaskHint': 'Another action people can check in for.',
  'create.addConstraint': 'Add a constraint',
  'create.taskOnce': 'Once',
  'create.hrMinutes': 'Elevated heart rate',
  'create.review': 'Review',
  'create.publish': 'Publish',
  'create.edit': 'Edit',
  'create.backToReview': 'Back to Review',
  'create.extraTaskPlaceholder': 'Read 10 pages',
  'create.needCheckins': 'Set how many check-ins.',
  'create.signIn': 'Sign in to create',
  'create.signInBody': 'Challenges are published under your account.',
  'create.backLobby': 'Back to Lobby',
  'board.remaining': 'Remaining',
  'board.caughtUp': 'Caught Up',
  'board.in': 'In',
  'board.checkedIn': 'Checked in',
  'board.out': 'Out',
  'board.donePeriod': 'done this period',
  'board.dropped': 'Dropped',
  'board.yourShareIfFinish': 'Your share if you finish:',
  'board.shareIfFinish': 'Share if you finish:',
  'board.yourShareIfPlace': 'Your share if you place:',
  'board.shareIfPlace': 'Share if you place:',
  'board.yourRank': 'Your Rank',
  'board.contestants': 'Contestants',
  'board.challengeLeader': 'Challenge Leader',
  'board.joinToRank': 'Join to rank',
  'board.noLeader': 'No score yet',
  'board.totalPrizePool': 'Total prize pool:',
  'note.boardPointsTitle': 'Board',
  'note.boardPoints':
    'Contestants are everyone in the challenge. Your Rank is your place by points. Challenge Leader is first place once someone has scored.',
  'note.contestantsTitle': 'Contestants',
  'note.contestants': 'How many people are in this challenge.',
  'note.yourRankTitle': 'Your Rank',
  'note.yourRank': 'Your place on the points leaderboard. Join to appear here.',
  'note.challengeLeaderTitle': 'Challenge Leader',
  'note.challengeLeader': 'Whoever has the most points right now.',
  'note.prizePoolTitle': 'Total prize pool',
  'note.prizePool': 'The prize as it stands now — entry fees plus any host funds.',
  'note.potTitle': 'Prize',
  'note.pot':
    'The prize is the total of entry fees plus any host funds. Remaining finishers split it evenly.',
  'note.potHostTitle': 'Prize',
  'note.potHost':
    'The host funds this prize. There is no entry fee. Remaining finishers split it evenly.',
  'note.buyInTitle': 'Entry fee',
  'note.buyIn':
    'Each person pays this to participate. It goes into the prize. Leave before live and it comes back in full.',
  'note.buyInFreeTitle': 'Entry',
  'note.buyInFree': 'FREE Entry. Joining does not take money from your wallet.',
  'note.boardTitle': 'Board',
  'note.board':
    'Empty until people join and check in. Remaining are still in. Caught Up have finished today’s required proof. Dropped missed or were removed.',
  'note.remainingTitle': 'Remaining',
  'note.remaining': 'Still in. Proven by check-in progress. Remaining finishers split the prize.',
  'note.caughtUpTitle': 'Caught Up',
  'note.caughtUp': 'Remaining people who already submitted today’s required proof.',
  'note.droppedTitle': 'Dropped',
  'note.dropped': 'Missed a required check-in, left, or were removed. They do not share the prize.',
  'note.shareTitle': 'Share if you finish',
  'note.share':
    'An estimate from the current prize and how many are still in. It changes when people join or drop.',
  'note.startTitle': 'Start',
  'note.startNeeded':
    'Starts when enough people have joined. This number will fall as people pay the entry fee.',
  'board.liveShare': 'Live share {amount}',
  'board.guarantee': 'Guaranteed Prize',
  'board.pot': 'Prize',
  'board.toStart': 'To start (1.5×)',
  'board.joined': 'Joined',
  'board.finished': 'Finished',
  'board.yourShare': 'Your share if you finish',
  'proof.flag': 'Flag proof',
  'proof.flagged': 'Flagged',
  'proof.flagReason': 'Heart-rate proof missing / not 30 min / not their workout.',
  'official.dayOf': 'Day {n} of {total}',
  'official.dayEndsCentral': 'Day ends 11:59 p.m. Central',
  'official.dayEndsLocal': 'That’s {time} where you are.',
  'official.dayCountdown': 'Ends in {time}',
  'money.realUsd': 'This is real money, 1:1 with USD.',
  'money.irreversible': 'This cannot be reversed.',
  'money.leavesNow': 'The exact amount leaves now.',
  'money.immediate': 'This happens immediately.',
  'wallet.finishChallenges': 'Finish challenges',
  'wallet.finishChallengesBody': 'Prizes pay Coins or $.',
  'wave.empty': 'Nobody’s waving. You can.',
  'wave.yours': 'Your Wave',
  'wave.add': 'Add Wave',
  'wave.recordAnother': 'Record another',
  'wave.share': 'Share Wave',
  'wave.new': 'New Wave',
  'wave.noun': 'Wave',
  'wave.hint': 'Nobody’s waving. You can.',
  'wave.cameraNeed': 'blOb needs the camera for Waves.',
  'wave.gone': 'This Wave is gone',
  'wave.goneBody': 'It may have expired, or the link is no longer valid.',
  'wave.posting': 'Posting your Wave…',
  'wave.posted': 'posted a Wave',
  'wave.chip': 'Optional. Shows a chip on your Wave.',
  'wave.library': 'Turn on library access in Settings so you can pick a photo or short video for your Wave.',
  'wave.signIn': 'You need to be signed in to post a Wave.',
  'wave.needMedia': 'Waves need a photo or a short video.',
  'wave.close': 'Close Wave',
  'wave.prev': 'Previous Wave',
  'wave.next': 'Next Wave',
  'round.empty': 'No Rounds yet. Post one from New Round.',
  'round.gone': 'This Round is gone.',
  'round.goneBody': 'It may have been deleted.',
  'round.new': 'New Round',
  'round.share': 'Share Round',
  'round.noun': 'Round',
  'round.title': 'Rounds',
  'round.fallback': 'Round',
  'round.notReady': 'Rounds aren’t ready. Use a Wave or a post.',
  'round.posted': 'posted a Round',
  'official.badge': 'Official.',
  'official.infinity': '∞',
  'official.friends': 'Friends',
  'official.sendConfirm': 'Check all three. This cannot be reversed.',
  'wallet.sent': 'Sent {amount}.',
  'mention.empty': 'No one to tag for this audience.',
  'mention.picker': 'Tag someone',
  'wall.empty': {
    gentle: 'Quiet wall. I’m here if someone writes.',
    neutral: 'Nothing on this wall yet.',
    honest: 'Blank wall. Someone has to go first.',
  },
  'wall.posted': 'Posted on {name}’s profile',
  'wall.writeOn': 'Write on {name}’s profile…',
  'profile.photosEmpty': 'Photos you post will live here.',
  'profile.challengesEmpty': 'Challenges you join will show up here.',
  'profile.photoShareFail': 'Photo updated. Couldn’t share to feed.',
  'wall.closed': 'You can’t post here anymore.',
  'wall.onHost': 'On {name}’s profile',
  'wall.remove': 'Remove from profile',
  'wall.allow': 'Allow others to post on your profile',
  'wall.muteMentions': 'Mute mention notifications',
  'wall.visibility': 'Who can see your profile',
  'privacy.title': 'Privacy',
  'privacy.posts': 'Default post audience',
  'privacy.postsHelp': 'New Home posts start as Public or Friends. You can change a post after you publish it.',
  'privacy.profile': 'Who can see your profile',
  'privacy.body': 'Body metrics stay private. They are not a toggle.',
  'privacy.public': 'Public',
  'privacy.friends': 'Friends',
  'wall.block': 'Block',
  'health.permissionDenied': 'Health access is off. Add a photo instead.',
  'health.empty':
    'No Watch workout in this window yet. Finish the workout on your Watch, wait a minute, or add a photo.',
  'health.useWorkout': 'Use this workout',
  'health.addPhoto': 'Add photo',
  'health.disconnect': 'We won’t read new workouts. Proofs you already checked in stay.',
  'health.offline': 'Connect to attach a workout',
  'health.connected': 'Connected',
  'health.notConnected': 'Not connected',
  'health.unavailable': 'Not available on this device',
  'health.chip': 'Use a workout',
  'health.sheetTitle': 'Use a workout',
  'health.confirm': 'Attach this to {title}?',
  'health.prompt': 'I see a {duration} {activity}. Begin check-in?',
  'health.checkoutPush': 'Post-workout selfie. Then Submit.',
  'health.faceHint': 'Same outfit. Face in frame.',
  'health.libraryBadge': 'Library',
  'health.liveBadge': 'Live',
  'health.tooShort': 'That workout is shorter than the required minutes.',
  'health.manualBadge': 'Entered in Health',
  'health.disconnectAction': 'Disconnect from blOb',
  'health.row': 'Apple Health',
  'health.rowAndroid': 'Health apps & watches',
  'health.androidHelper':
    'Uses workouts already on this phone (Watch, Fitbit, Garmin, and others if they sync here).',
  'health.install': 'Install Health Connect to use workouts.',
  'health.installSubtitle': 'Install Health Connect',
  'health.attachFailed': 'Couldn’t attach that workout. Try the camera.',
  'health.logIt': 'Check in',
  'health.notNow': 'Not now',
  'health.reads': 'We read workouts, heart rate during those workouts, calories, and distance.',
  'health.lastSynced': 'Last synced {when}',
  'health.syncFailed': 'Couldn’t sync. Pull to refresh on the workout sheet.',
  'health.proofTitle': 'Workout proof',
  'health.startWatch': 'Start on Watch',
  'health.startedWatch': 'Started on your Watch.',
  'health.noWatch': 'Start a workout in Fitness, then come back.',
  'health.startWatchFail': 'Use the camera, or start a workout in Fitness.',
  'checkin.begin': 'Begin',
  'checkin.continue': 'Continue',
  'checkin.submit': 'Submit',
  'checkin.checkedIn': 'Checked in',
  'checkin.imStarting': 'I’m starting',
  'checkin.emptyBob': 'Start now. Finish when the work is done.',
  'checkin.successBob': 'You showed up. That counts.',
  'checkin.offlineBob': 'No signal. I’ll wait here.',
  'checkin.permissionBob': 'Camera is off. I can’t take the proof without it.',
  'checkin.uploadFailBob': 'That photo didn’t make it. Try once more.',
  'checkin.alreadyBob': 'Already counted today. Come back for the next window.',
  'checkin.notLiveBob': 'This challenge isn’t taking check-ins right now.',
  'checkin.submitBanner': 'You started. Submit before 11:59 p.m. Central.',
} as const;

export type CopyKey = keyof typeof STRINGS;

type CopyNode = string | { readonly [K in CopyTone]: string };

export function interpolateCopy(template: string, vars?: Record<string, string | number>): string {
  if (!vars) {
    return template;
  }
  return template.replace(/\{(\w+)\}/g, (_, name: string) =>
    vars[name] == null ? `{${name}}` : String(vars[name]),
  );
}

function interpolate(template: string, vars?: Record<string, string | number>): string {
  return interpolateCopy(template, vars);
}

export function asCopyTone(value: unknown): CopyTone {
  if (value === 'gentle' || value === 'neutral' || value === 'honest') {
    return value;
  }
  return 'neutral';
}

export function copy(key: CopyKey, tone: CopyTone = 'neutral', vars?: Record<string, string | number>): string {
  const node = STRINGS[key] as CopyNode;
  const template = typeof node === 'string' ? node : (node[tone] ?? node.neutral);
  return interpolate(template, vars);
}

export const COPY_TONE_OPTIONS: { value: CopyTone; key: CopyKey }[] = [
  { value: 'gentle', key: 'profile.toneGentle' },
  { value: 'neutral', key: 'profile.toneNeutral' },
  { value: 'honest', key: 'profile.toneHonest' },
];
