export const COPY_TONES = ['gentle', 'neutral', 'honest'] as const;

export type CopyTone = (typeof COPY_TONES)[number];

const STRINGS = {
  'bfp.sliderHint': {
    gentle: 'Move this until this Blob looks like you do right now.',
    neutral: 'Match the slider to your current body fat, or type the exact %.',
    honest: 'This is what you look like today, not what you wish. Slide until it matches, or type the number if you have it.',
  },
  'bfp.enterExact': 'Enter exact %',
  'bfp.exactLabel': 'Exact body fat %',
  'training.lastDoneHint': 'When is the last time you participated in these activities?',
  'training.aims': 'Aims',
  'profile.update': 'Update profile',
  'profile.saved': 'Saved.',
  'profile.toneLabel': 'How should Bob talk to you?',
  'profile.toneGentle': 'Gentle',
  'profile.toneNeutral': 'Neutral',
  'profile.toneHonest': 'Honest',
  'profile.encouragementLabel': 'How should Bob nudge you?',
  'profile.encouragementHelp': 'Alerts from Bob when you check in, miss, or come back. Separate from how the app talks to you.',
  'error.uploadPhoto': 'Couldn’t upload photo. Try again.',
  'error.preferenceSave': 'Couldn’t save that preference. You can set it later.',
  'error.notEnoughPeople': 'Not enough people joined.',
  'post.deleteConfirm': 'Delete?',
  'post.delete': 'Delete',
  'error.deletePost': 'Couldn’t delete.',
  'account.passwordHint': 'Use upper and lower case, a number, and a symbol.',
  'account.passwordUpdated': 'Password updated.',
  'error.passwordWeak': 'Needs a lowercase, uppercase, number, and symbol.',
  'error.passwordSame': 'Pick a different password.',
  'error.passwordSession': 'Sign in again, then try.',
  'error.passwordUpdate': 'Couldn’t update password. Try again.',
  'error.passwordMismatch': 'Those passwords don’t match.',
  'auth.welcome': {
    gentle: 'Welcome back. I saved you a spot.',
    neutral: 'Welcome back.',
    honest: 'You’re late. Sign in.',
  },
  'auth.subtitle': {
    gentle: 'I’m Bob. We can go slow. We still go.',
    neutral: 'I’m Bob. Sign in and we’ll get to work.',
    honest: 'I’m Bob. Effort is the only door. Sign in.',
  },
  'auth.signingIn': {
    gentle: 'Almost in. Don’t wander off.',
    neutral: 'Signing you in.',
    honest: 'Waiting on you, not the internet.',
  },
  'auth.createAccount': 'Create account',
  'auth.signIn': 'Sign in',
  'auth.waitRetry': 'Please wait a few seconds and try again.',
  'auth.emailExists': 'That email already has an account. Sign in.',
  'auth.network': 'Couldn’t reach the server. Try again.',
  'auth.newHere': 'New here?',
  'home.header': 'Home',
  'home.loading': {
    gentle: 'Checking who showed up for you.',
    neutral: 'Checking who showed up.',
    honest: 'If this takes a while, it is not because you stretched.',
  },
  'home.error': {
    gentle: 'Home didn’t load. Try again when you’re ready.',
    neutral: 'Home didn’t load.',
    honest: 'Home didn’t load. Tapping again is allowed.',
  },
  'home.empty': {
    gentle: 'Nobody you know has posted. You can go first. I will watch.',
    neutral: 'Nobody you know has posted.',
    honest: 'Empty on purpose until someone posts. That can be you.',
  },
  'home.composer': {
    gentle: 'What did you do? Even a little counts.',
    neutral: 'What did you do?',
    honest: 'What did you actually do?',
  },
  'lobby.subtitle': 'Find a challenge. Pay the entry fee. Prove the work.',
  'lobby.loading': {
    gentle: 'Looking for Challenges. Stay here.',
    neutral: 'Looking for Challenges.',
    honest: 'Looking for Challenges. They will not find you first.',
  },
  'lobby.empty': {
    gentle: 'Nothing open yet. You could start one. I’ll stand next to it.',
    neutral: 'Nothing open yet. You could start one.',
    honest: 'Nothing open. Create one or go home. Those are the options.',
  },
  'lobby.unreachable': 'Couldn’t load the Lobby.',
  'lobby.railHosting': 'Hosting',
  'lobby.railActive': 'Active',
  'lobby.railOfficial': 'Official',
  'lobby.railFriends': 'Friends',
  'feed.railActive': 'Active',
  'feed.featuredChallenge': 'Featured Challenge',
  'feed.peopleYouMayKnow': 'People you may know',
  'feed.youreIn': 'You’re in',
  'feed.notJoined': 'Not joined',
  'feed.openChallenge': 'Open',
  'feed.logToday': 'Check in today',
  'lobby.friendsHosting': '{name} is hosting',
  'lobby.friendsJoined': '{name} joined',
  'create.friendsOfFriends': 'Visible to friends of friends',
  'geo.unavailable': 'Sorry, this Challenge isn’t available in your State.',
  'challenge.privateWallTitle': 'Private challenge',
  'challenge.privateWall': 'This is a private challenge. Only competitors can open it.',
  'feed.checkedIn': 'Checked in ·',
  'friends.loading': {
    gentle: 'Finding your people.',
    neutral: 'Finding your people.',
    honest: 'Looking up who actually knows you.',
  },
  'friends.empty': {
    gentle: 'No friends yet. That’s a beginning, not a verdict.',
    neutral: 'No friends yet.',
    honest: 'No friends yet. Search. Send a request. Waiting is not a strategy.',
  },
  'friends.noneMatch': {
    gentle: 'Nobody matches that. Try a different name.',
    neutral: 'Nobody matches that.',
    honest: 'Nobody matches that. Check the spelling before you invent a person.',
  },
  'friends.searchPlaceholder': 'Name, @username, email, or phone',
  'alerts.empty': {
    gentle: 'Nothing new. I’ll tap you when there is.',
    neutral: 'Nothing new.',
    honest: 'Nothing new. That is not the same as done.',
  },
  'alerts.loading': 'Checking your inbox.',
  'alerts.error': 'Couldn’t load notifications.',
  'messages.empty': {
    gentle: 'No chats yet. Say something kind. Or useful. Both is better.',
    neutral: 'No chats yet.',
    honest: 'No chats. Messages do not send themselves.',
  },
  'messages.error': 'Couldn’t load messages.',
  'messages.loading': 'Opening your inbox.',
  'profile.loading': {
    gentle: 'Looking you up.',
    neutral: 'Looking you up.',
    honest: 'Loading the facts. Not the story you tell yourself.',
  },
  'profile.error': 'Couldn’t load your profile.',
  'profile.notFound': 'Couldn’t load that profile.',
  'notFound.title': {
    gentle: 'That door doesn’t go anywhere. Let’s go back.',
    neutral: 'That door doesn’t go anywhere.',
    honest: 'That door doesn’t go anywhere. Stop knocking.',
  },
  'challenge.logClosed': 'Check-in is closed.',
  'challenge.notStarted': 'This challenge hasn’t started yet.',
  'challenge.eliminated': 'You have been eliminated.',
  'challenge.cancel': 'Cancel challenge',
  'challenge.delete': 'Delete',
  'challenge.cancelKeep': 'Keep',
  'challenge.leave': 'Leave',
  'challenge.leaveConfirm': 'Leave this challenge? Your entry goes back to your wallet.',
  'challenge.leaveKeep': 'Stay',
  'error.leaveChallenge': 'Couldn’t leave. Try again.',
  'challenge.startMovedTitle': 'Start moved',
  'challenge.keepDays': 'Keep {n} days',
  'challenge.shortenDay': 'Shorten by 1 day',
  'challenge.startMovedLater': 'Not now',
  'challenge.pickStart': 'Pick a start date',
  'error.startUpdate': 'Couldn’t update the start.',
  'error.cancelChallenge': 'Couldn’t cancel. Try again.',
  'error.composerUpload': 'Couldn’t upload that. The post wasn’t sent.',
  'error.usePhotoOrVideo': 'Use a photo or video.',
  'challenge.startTomorrow': 'Start tomorrow',
  'challenge.editChallenge': 'Edit challenge',
  'challenge.waitingToStart': 'Waiting to start.',
  'create.minToStart': 'Min to start',
  'create.minToStartHint': 'Includes you. If fewer people have joined at start, it waits and the start moves to the next day.',
  'create.editTitle': 'Edit Challenge',
  'create.save': 'Save',
  'challenge.cancelConfirmCoins': 'Cancel this challenge? Anyone who paid gets their coins back.',
  'challenge.cancelConfirmFree': 'Cancel this challenge? It will disappear from Lobby and the feed.',
  'challenge.cancelled': 'This challenge was cancelled.',
  'challenge.cancelledToast': 'Challenge cancelled.',
  'challenge.notFound': 'Challenge not found.',
  'challenge.joinFirst': 'Join first.',
  'create.screenTitle': 'New Challenge',
  'create.currency': 'Currency',
  'create.coins': 'Coins',
  'create.bucks': '$',
  'create.youFundPrize': 'You fund the prize.',
  'create.hostPrize': 'Host prize',
  'create.totalPrizePool': 'Total prize',
  'create.realMoneyFund': 'For challenges with real money, you fund this amount.',
  'create.buyIn': 'Entry fee',
  'create.type': 'Type',
  'create.titleLabel': 'Title',
  'create.titlePlaceholder': 'Morning miles',
  'create.descriptionLabel': 'Description',
  'create.descriptionPlaceholder': 'Optional',
  'create.photoLabel': 'Challenge photo',
  'create.photoHelper': 'Shown on Lobby and when people share this challenge.',
  'create.photoAdd': 'Add photo',
  'create.photoCamera': 'Camera',
  'create.photoGallery': 'Gallery',
  'create.photoReplace': 'Replace',
  'create.photoRemove': 'Remove',
  'create.start': 'Start',
  'create.duration': 'Duration',
  'create.days': 'Days',
  'create.taskLabel': 'Task',
  'create.taskPlaceholder': 'Run 1 mile',
  'create.frequency': 'Frequency',
  'create.checkins': 'Check-ins',
  'create.proof': 'Proof',
  'create.proofs': 'Proofs',
  'create.addProof': 'Add proof',
  'create.proofPreset': 'Before · After · heart rate',
  'create.proofsHelper': "Say the action. 'Photo' is not enough.",
  'create.proofFallback': 'Post a photo of the work.',
  'create.proofPhoto': 'Photo',
  'create.proofVideo': 'Video',
  'create.proofCheckin': 'Check-in',
  'create.proofHonor': 'Honor',
  'create.proofHr': 'Heart rate',
  'create.visibility': 'Visibility',
  'create.public': 'Public',
  'create.friends': 'Friends',
  'create.invite': 'Invite',
  'create.submit': 'Create',
  'create.advanced': 'Advanced',
  'create.simple': 'Simple',
  'create.setHostPrize': 'Set a host prize.',
  'create.needTitle': 'Give it a title.',
  'create.needStart': 'Pick a start.',
  'create.startFuture': 'Start has to be in the future.',
  'create.needDuration': 'Duration has to be at least 1 day.',
  'create.needTask': 'Add a task.',
  'create.needExtraTask': 'Name each extra task, or remove it.',
  'create.addTask': 'Add another task',
  'create.taskOnce': 'Once',
  'create.hrMinutes': 'Elevated heart rate',
  'create.review': 'Review',
  'create.publish': 'Publish',
  'create.edit': 'Edit',
  'create.backToReview': 'Back to Review',
  'create.extraTaskPlaceholder': 'Read 10 pages',
  'create.needCheckins': 'Set how many check-ins.',
  'create.signIn': 'Sign in to create',
  'create.signInBody': 'Challenges are published under your account.',
  'create.backLobby': 'Back to Lobby',
  'board.remaining': 'Remaining',
  'board.caughtUp': 'Caught Up',
  'board.donePeriod': 'done this period',
  'board.dropped': 'Dropped',
  'board.yourShareIfFinish': 'Your share if you finish:',
  'board.shareIfFinish': 'Share if you finish:',
  'note.potTitle': 'Prize',
  'note.pot':
    'Prize grows as people pay the entry fee. On publish it may be only your amount, or $0 until the first join.',
  'note.buyInTitle': 'Entry fee',
  'note.buyIn': 'Each person pays this to join. It does not change.',
  'note.boardTitle': 'Board',
  'note.board':
    'Empty until people join and check in. Remaining are still in. Caught Up have finished today’s required proof. Dropped missed or were removed.',
  'note.shareTitle': 'Share if you finish',
  'note.share':
    'An estimate from the current prize and how many are still in. It changes when people join or drop.',
  'note.startTitle': 'Start',
  'note.startNeeded':
    'Starts when enough people have joined. This number will fall as people pay the entry fee.',
  'board.liveShare': 'Live share {amount}',
  'board.guarantee': 'Guarantee',
  'board.pot': 'Prize',
  'board.toStart': 'To start (1.5×)',
  'board.joined': 'Joined',
  'board.finished': 'Finished',
  'board.yourShare': 'Your share if you finish',
  'proof.flag': 'Flag proof',
  'proof.flagged': 'Flagged',
  'proof.flagReason': 'HR proof missing / not 30 min / not their workout.',
  'official.dayOf': 'Day {n} of {total}',
  'official.dayEndsCentral': 'Day ends 11:59 p.m. Central',
  'official.dayEndsLocal': 'That’s {time} where you are.',
  'official.dayCountdown': 'Ends in {time}',
  'money.realUsd': 'This is real money, 1:1 with USD.',
  'money.irreversible': 'This cannot be reversed.',
  'money.leavesNow': 'The exact amount leaves now.',
  'money.immediate': 'This happens immediately.',
  'wallet.finishChallenges': 'Finish challenges',
  'wallet.finishChallengesBody': 'Prizes pay Coins or $.',
  'wave.empty': 'Nobody’s waving. You can.',
  'wave.yours': 'Your Wave',
  'wave.add': 'Add Wave',
  'wave.share': 'Share Wave',
  'wave.new': 'New Wave',
  'wave.noun': 'Wave',
  'wave.hint': 'Nobody’s waving. You can.',
  'wave.cameraNeed': 'blOb needs the camera for Waves.',
  'wave.gone': 'This Wave is gone',
  'wave.goneBody': 'It may have expired, or the link is no longer valid.',
  'wave.posting': 'Posting your Wave…',
  'wave.posted': 'posted a Wave',
  'wave.chip': 'Optional. Shows a chip on your Wave.',
  'wave.library': 'Turn on library access in Settings so you can pick a photo or short video for your Wave.',
  'wave.signIn': 'You need to be signed in to post a Wave.',
  'wave.needMedia': 'Waves need a photo or a short video.',
  'wave.close': 'Close Wave',
  'wave.prev': 'Previous Wave',
  'wave.next': 'Next Wave',
  'round.empty': 'No Rounds yet.',
  'round.new': 'New Round',
  'round.share': 'Share Round',
  'round.noun': 'Round',
  'round.title': 'Rounds',
  'round.fallback': 'Round',
  'round.notReady': 'Rounds aren’t ready. Use a Wave or a post.',
  'round.posted': 'posted a Round',
  'official.badge': 'Official.',
  'official.infinity': '∞',
  'official.friends': 'Friends',
  'official.sendConfirm': 'Check all three. This cannot be reversed.',
  'wallet.sent': 'Sent {amount}.',
  'mention.empty': 'No one to tag for this audience.',
  'mention.picker': 'Tag someone',
  'wall.empty': {
    gentle: 'Quiet wall. I’m here if someone writes.',
    neutral: 'Nothing on this wall yet.',
    honest: 'Blank wall. Someone has to go first.',
  },
  'wall.posted': 'Posted on {name}’s profile',
  'wall.closed': 'You can’t post here anymore.',
  'wall.onHost': 'On {name}’s profile',
  'wall.remove': 'Remove from profile',
  'wall.allow': 'Allow others to post on your profile',
  'wall.muteMentions': 'Mute mention notifications',
  'wall.visibility': 'Who can see your profile',
  'privacy.title': 'Privacy',
  'privacy.posts': 'Default post audience',
  'privacy.postsHelp': 'New Home posts start as Public or Friends. You can change a post after you publish it.',
  'privacy.profile': 'Who can see your profile',
  'privacy.body': 'Body metrics stay private. They are not a toggle.',
  'privacy.public': 'Public',
  'privacy.friends': 'Friends',
  'wall.block': 'Block',
  'health.permissionDenied': 'We’ll use the camera instead.',
  'health.empty': 'I don’t see a workout yet. You can still prove it the human way.',
  'health.disconnect': 'We won’t read new workouts. Proofs you already checked in stay.',
  'health.offline': 'Connect to attach a workout',
  'health.connected': 'Connected',
  'health.notConnected': 'Not connected',
  'health.unavailable': 'Not available on this device',
  'health.chip': 'Use a workout',
  'health.sheetTitle': 'Use a workout',
  'health.confirm': 'Attach this to {title}?',
  'health.prompt': 'I see a {duration} {activity}. Begin check-in?',
  'health.checkoutPush': 'Post-workout selfie. Then Submit.',
  'health.faceHint': 'Same outfit. Face in frame.',
  'health.libraryBadge': 'Library',
  'health.liveBadge': 'Live',
  'health.tooShort': 'That workout is shorter than the required minutes.',
  'health.manualBadge': 'Entered in Health',
  'health.disconnectAction': 'Disconnect from blOb',
  'health.row': 'Apple Health',
  'health.rowAndroid': 'Health apps & watches',
  'health.androidHelper':
    'Uses workouts already on this phone (Watch, Fitbit, Garmin, and others if they sync here).',
  'health.install': 'Install Health Connect to use workouts.',
  'health.installSubtitle': 'Install Health Connect',
  'health.attachFailed': 'Couldn’t attach that workout. Try the camera.',
  'health.logIt': 'Check in',
  'health.notNow': 'Not now',
  'health.reads': 'We read workouts, heart rate during those workouts, calories, and distance.',
  'health.lastSynced': 'Last synced {when}',
  'health.syncFailed': 'Couldn’t sync. Pull to refresh on the workout sheet.',
  'health.proofTitle': 'Workout proof',
  'health.startWatch': 'Start on Watch',
  'health.startedWatch': 'Started on your Watch.',
  'health.noWatch': 'Start a workout in Fitness, then come back.',
  'health.startWatchFail': 'Use the camera, or start a workout in Fitness.',
  'checkin.begin': 'Begin check-in',
  'checkin.continue': 'Continue check-in',
  'checkin.submit': 'Submit',
  'checkin.checkedIn': 'Checked in',
  'checkin.imStarting': 'I’m starting',
  'checkin.emptyBob': 'Start now. Finish when the work is done.',
  'checkin.submitBanner': 'You started. Submit before 11:59 p.m. Central.',
} as const;

export type CopyKey = keyof typeof STRINGS;

type CopyNode = string | { readonly [K in CopyTone]: string };

export function interpolateCopy(template: string, vars?: Record<string, string | number>): string {
  if (!vars) {
    return template;
  }
  return template.replace(/\{(\w+)\}/g, (_, name: string) =>
    vars[name] == null ? `{${name}}` : String(vars[name]),
  );
}

function interpolate(template: string, vars?: Record<string, string | number>): string {
  return interpolateCopy(template, vars);
}

export function asCopyTone(value: unknown): CopyTone {
  if (value === 'gentle' || value === 'neutral' || value === 'honest') {
    return value;
  }
  return 'neutral';
}

export function copy(key: CopyKey, tone: CopyTone = 'neutral', vars?: Record<string, string | number>): string {
  const node = STRINGS[key] as CopyNode;
  const template = typeof node === 'string' ? node : (node[tone] ?? node.neutral);
  return interpolate(template, vars);
}

export const COPY_TONE_OPTIONS: { value: CopyTone; key: CopyKey }[] = [
  { value: 'gentle', key: 'profile.toneGentle' },
  { value: 'neutral', key: 'profile.toneNeutral' },
  { value: 'honest', key: 'profile.toneHonest' },
];
