-- Official lift exercise catalog.
--
-- GENERATED FILE. Do not hand-edit. Regenerate with:
--   node scripts/buildLiftSeed.mjs
-- The source of truth is lib/lift/catalogData.ts, which the app also reads so typeahead works
-- offline on iOS, Android, and Web.
--
-- Re-runnable: an existing id is refreshed, never duplicated. Nothing is deleted here, and no
-- policy or grant is changed by this file.

insert into public.lift_exercises (id, name, primary_muscle, secondary_muscles, aliases)
values
  ('flat-bb-bench-press', 'Flat BB Bench Press', 'chest', array['triceps', 'shoulders']::text[], array['flat barbell bench press', 'flat bb bench', 'flat barbell bench']::text[]),
  ('incline-bb-bench-press', 'Incline BB Bench Press', 'chest', array['triceps', 'shoulders']::text[], array['incline barbell bench press', 'incline bb bench', 'incline barbell bench']::text[]),
  ('low-incline-bb-bench-press', 'Low-Incline BB Bench Press', 'chest', array['triceps', 'shoulders']::text[], array['low incline barbell bench press', 'low incline bb bench', 'low incline barbell bench']::text[]),
  ('decline-bb-bench-press', 'Decline BB Bench Press', 'chest', array['triceps', 'shoulders']::text[], array['decline barbell bench press', 'decline bb bench', 'decline barbell bench']::text[]),
  ('wide-grip-bb-bench-press', 'Wide-Grip BB Bench Press', 'chest', array['triceps', 'shoulders']::text[], array['wide grip barbell bench press', 'wide grip bb bench', 'wide grip barbell bench']::text[]),
  ('wide-grip-incline-bb-bench-press', 'Wide-Grip Incline BB Bench Press', 'chest', array['triceps', 'shoulders']::text[], array['wide grip incline barbell bench press', 'wide grip incline bb bench', 'wide grip incline barbell bench']::text[]),
  ('reverse-grip-bb-bench-press', 'Reverse-Grip BB Bench Press', 'chest', array['triceps', 'shoulders']::text[], array['reverse grip barbell bench press', 'reverse grip bb bench', 'reverse grip barbell bench']::text[]),
  ('reverse-grip-incline-bb-bench-press', 'Reverse-Grip Incline BB Bench Press', 'chest', array['triceps', 'shoulders']::text[], array['reverse grip incline barbell bench press', 'reverse grip incline bb bench', 'reverse grip incline barbell bench']::text[]),
  ('paused-bb-bench-press', 'Paused BB Bench Press', 'chest', array['triceps', 'shoulders']::text[], array['paused barbell bench press', 'paused bb bench', 'paused barbell bench']::text[]),
  ('bb-floor-press', 'BB Floor Press', 'chest', array['triceps', 'shoulders']::text[], array['barbell floor press']::text[]),
  ('spoto-press', 'Spoto Press', 'chest', array['triceps', 'shoulders']::text[], '{}'::text[]),
  ('bb-board-press', 'BB Board Press', 'chest', array['triceps', 'shoulders']::text[], array['barbell board press']::text[]),
  ('bench-pin-press', 'Bench Pin Press', 'chest', array['triceps', 'shoulders']::text[], '{}'::text[]),
  ('larsen-press', 'Larsen Press', 'chest', array['triceps', 'shoulders']::text[], '{}'::text[]),
  ('feet-up-bb-bench-press', 'Feet-Up BB Bench Press', 'chest', array['triceps', 'shoulders']::text[], array['feet up barbell bench press', 'feet up bb bench', 'feet up barbell bench']::text[]),
  ('guillotine-press', 'Guillotine Press', 'chest', array['triceps', 'shoulders']::text[], '{}'::text[]),
  ('banded-bb-bench-press', 'Banded BB Bench Press', 'chest', array['triceps', 'shoulders']::text[], array['banded barbell bench press', 'banded bb bench', 'banded barbell bench']::text[]),
  ('chain-bb-bench-press', 'Chain BB Bench Press', 'chest', array['triceps', 'shoulders']::text[], array['chain barbell bench press', 'chain bb bench', 'chain barbell bench']::text[]),
  ('flat-sm-bench-press', 'Flat SM Bench Press', 'chest', array['triceps', 'shoulders']::text[], array['flat smith bench press', 'flat sm bench', 'flat smith bench']::text[]),
  ('incline-sm-bench-press', 'Incline SM Bench Press', 'chest', array['triceps', 'shoulders']::text[], array['incline smith bench press', 'incline sm bench', 'incline smith bench']::text[]),
  ('decline-sm-bench-press', 'Decline SM Bench Press', 'chest', array['triceps', 'shoulders']::text[], array['decline smith bench press', 'decline sm bench', 'decline smith bench']::text[]),
  ('sm-floor-press', 'SM Floor Press', 'chest', array['triceps', 'shoulders']::text[], array['smith floor press']::text[]),
  ('flat-db-bench-press', 'Flat DB Bench Press', 'chest', array['triceps', 'shoulders']::text[], array['flat dumbbell bench press', 'flat db bench', 'flat dumbbell bench']::text[]),
  ('incline-db-bench-press', 'Incline DB Bench Press', 'chest', array['triceps', 'shoulders']::text[], array['incline dumbbell bench press', 'incline db bench', 'incline dumbbell bench']::text[]),
  ('low-incline-db-bench-press', 'Low-Incline DB Bench Press', 'chest', array['triceps', 'shoulders']::text[], array['low incline dumbbell bench press', 'low incline db bench', 'low incline dumbbell bench']::text[]),
  ('decline-db-bench-press', 'Decline DB Bench Press', 'chest', array['triceps', 'shoulders']::text[], array['decline dumbbell bench press', 'decline db bench', 'decline dumbbell bench']::text[]),
  ('neutral-grip-db-bench-press', 'Neutral-Grip DB Bench Press', 'chest', array['triceps', 'shoulders']::text[], array['neutral grip dumbbell bench press', 'neutral grip db bench', 'neutral grip dumbbell bench']::text[]),
  ('alternating-db-bench-press', 'Alternating DB Bench Press', 'chest', array['triceps', 'shoulders']::text[], array['alternating dumbbell bench press', 'alternating db bench', 'alternating dumbbell bench']::text[]),
  ('single-arm-db-bench-press', 'Single-Arm DB Bench Press', 'chest', array['triceps', 'shoulders']::text[], array['single arm dumbbell bench press', 'single arm db bench', 'single arm dumbbell bench']::text[]),
  ('feet-up-db-bench-press', 'Feet-Up DB Bench Press', 'chest', array['triceps', 'shoulders']::text[], array['feet up dumbbell bench press', 'feet up db bench', 'feet up dumbbell bench']::text[]),
  ('db-floor-press', 'DB Floor Press', 'chest', array['triceps', 'shoulders']::text[], array['dumbbell floor press']::text[]),
  ('db-squeeze-press', 'DB Squeeze Press', 'chest', array['triceps', 'shoulders']::text[], array['dumbbell squeeze press']::text[]),
  ('incline-db-squeeze-press', 'Incline DB Squeeze Press', 'chest', array['triceps', 'shoulders']::text[], array['incline dumbbell squeeze press']::text[]),
  ('twisting-db-bench-press', 'Twisting DB Bench Press', 'chest', array['triceps', 'shoulders']::text[], array['twisting dumbbell bench press', 'twisting db bench', 'twisting dumbbell bench']::text[]),
  ('machine-chest-press', 'Machine Chest Press', 'chest', array['triceps', 'shoulders']::text[], '{}'::text[]),
  ('incline-machine-chest-press', 'Incline Machine Chest Press', 'chest', array['triceps', 'shoulders']::text[], '{}'::text[]),
  ('decline-machine-chest-press', 'Decline Machine Chest Press', 'chest', array['triceps', 'shoulders']::text[], '{}'::text[]),
  ('converging-chest-press', 'Converging Chest Press', 'chest', array['triceps', 'shoulders']::text[], '{}'::text[]),
  ('iso-lateral-chest-press', 'Iso-Lateral Chest Press', 'chest', array['triceps', 'shoulders']::text[], '{}'::text[]),
  ('plate-loaded-chest-press', 'Plate-Loaded Chest Press', 'chest', array['triceps', 'shoulders']::text[], '{}'::text[]),
  ('plate-loaded-incline-chest-press', 'Plate-Loaded Incline Chest Press', 'chest', array['triceps', 'shoulders']::text[], '{}'::text[]),
  ('vertical-chest-press', 'Vertical Chest Press', 'chest', array['triceps', 'shoulders']::text[], '{}'::text[]),
  ('standing-cable-chest-press', 'Standing Cable Chest Press', 'chest', array['triceps', 'shoulders']::text[], '{}'::text[]),
  ('seated-cable-chest-press', 'Seated Cable Chest Press', 'chest', array['triceps', 'shoulders']::text[], '{}'::text[]),
  ('single-arm-cable-chest-press', 'Single-Arm Cable Chest Press', 'chest', array['triceps', 'shoulders']::text[], '{}'::text[]),
  ('landmine-press', 'Landmine Press', 'chest', array['triceps', 'shoulders']::text[], '{}'::text[]),
  ('half-kneeling-landmine-press', 'Half-Kneeling Landmine Press', 'chest', array['triceps', 'shoulders']::text[], '{}'::text[]),
  ('flat-db-fly', 'Flat DB Fly', 'chest', array['shoulders']::text[], array['flat dumbbell fly']::text[]),
  ('incline-db-fly', 'Incline DB Fly', 'chest', array['shoulders']::text[], array['incline dumbbell fly']::text[]),
  ('decline-db-fly', 'Decline DB Fly', 'chest', array['shoulders']::text[], array['decline dumbbell fly']::text[]),
  ('pec-deck', 'Pec Deck', 'chest', array['shoulders']::text[], '{}'::text[]),
  ('machine-chest-fly', 'Machine Chest Fly', 'chest', array['shoulders']::text[], '{}'::text[]),
  ('incline-machine-fly', 'Incline Machine Fly', 'chest', array['shoulders']::text[], '{}'::text[]),
  ('cable-fly', 'Cable Fly', 'chest', array['shoulders']::text[], '{}'::text[]),
  ('incline-cable-fly', 'Incline Cable Fly', 'chest', array['shoulders']::text[], '{}'::text[]),
  ('decline-cable-fly', 'Decline Cable Fly', 'chest', array['shoulders']::text[], '{}'::text[]),
  ('low-to-high-cable-fly', 'Low-to-High Cable Fly', 'chest', array['shoulders']::text[], '{}'::text[]),
  ('high-to-low-cable-fly', 'High-to-Low Cable Fly', 'chest', array['shoulders']::text[], '{}'::text[]),
  ('single-arm-cable-fly', 'Single-Arm Cable Fly', 'chest', array['shoulders']::text[], '{}'::text[]),
  ('standing-cable-crossover', 'Standing Cable Crossover', 'chest', array['shoulders']::text[], '{}'::text[]),
  ('kneeling-cable-crossover', 'Kneeling Cable Crossover', 'chest', array['shoulders']::text[], '{}'::text[]),
  ('bench-cable-fly', 'Bench Cable Fly', 'chest', array['shoulders']::text[], '{}'::text[]),
  ('svend-press', 'Svend Press', 'chest', array['shoulders']::text[], '{}'::text[]),
  ('chest-dip', 'Chest Dip', 'chest', array['triceps', 'shoulders']::text[], '{}'::text[]),
  ('weighted-chest-dip', 'Weighted Chest Dip', 'chest', array['triceps', 'shoulders']::text[], '{}'::text[]),
  ('assisted-chest-dip', 'Assisted Chest Dip', 'chest', array['triceps', 'shoulders']::text[], '{}'::text[]),
  ('ring-dip', 'Ring Dip', 'chest', array['triceps', 'shoulders']::text[], '{}'::text[]),
  ('push-up', 'Push-Up', 'chest', array['triceps', 'shoulders']::text[], array['pushup']::text[]),
  ('weighted-push-up', 'Weighted Push-Up', 'chest', array['triceps', 'shoulders']::text[], array['weighted pushup']::text[]),
  ('incline-push-up', 'Incline Push-Up', 'chest', array['triceps', 'shoulders']::text[], array['incline pushup']::text[]),
  ('decline-push-up', 'Decline Push-Up', 'chest', array['triceps', 'shoulders']::text[], array['decline pushup']::text[]),
  ('deficit-push-up', 'Deficit Push-Up', 'chest', array['triceps', 'shoulders']::text[], array['deficit pushup']::text[]),
  ('wide-push-up', 'Wide Push-Up', 'chest', array['triceps', 'shoulders']::text[], array['wide pushup']::text[]),
  ('archer-push-up', 'Archer Push-Up', 'chest', array['triceps', 'shoulders']::text[], array['archer pushup']::text[]),
  ('ring-push-up', 'Ring Push-Up', 'chest', array['triceps', 'shoulders']::text[], array['ring pushup']::text[]),
  ('plyo-push-up', 'Plyo Push-Up', 'chest', array['triceps', 'shoulders']::text[], array['plyo pushup']::text[]),
  ('banded-push-up', 'Banded Push-Up', 'chest', array['triceps', 'shoulders']::text[], array['banded pushup']::text[]),
  ('pseudo-planche-push-up', 'Pseudo Planche Push-Up', 'chest', array['triceps', 'shoulders']::text[], array['pseudo planche pushup']::text[]),
  ('push-up-plus', 'Push-Up Plus', 'chest', array['triceps', 'shoulders']::text[], array['pushup plus']::text[]),
  ('db-pullover', 'DB Pullover', 'chest', array['back', 'triceps']::text[], array['dumbbell pullover']::text[]),
  ('bb-pullover', 'BB Pullover', 'chest', array['back', 'triceps']::text[], array['barbell pullover']::text[]),
  ('pull-up', 'Pull-Up', 'back', array['biceps', 'forearms']::text[], array['pullup']::text[]),
  ('weighted-pull-up', 'Weighted Pull-Up', 'back', array['biceps', 'forearms']::text[], array['weighted pullup']::text[]),
  ('wide-grip-pull-up', 'Wide-Grip Pull-Up', 'back', array['biceps', 'forearms']::text[], array['wide grip pullup']::text[]),
  ('neutral-grip-pull-up', 'Neutral-Grip Pull-Up', 'back', array['biceps', 'forearms']::text[], array['neutral grip pullup']::text[]),
  ('chin-up', 'Chin-Up', 'back', array['biceps', 'forearms']::text[], array['chinup']::text[]),
  ('weighted-chin-up', 'Weighted Chin-Up', 'back', array['biceps', 'forearms']::text[], array['weighted chinup']::text[]),
  ('commando-pull-up', 'Commando Pull-Up', 'back', array['biceps', 'forearms']::text[], array['commando pullup']::text[]),
  ('archer-pull-up', 'Archer Pull-Up', 'back', array['biceps', 'forearms']::text[], array['archer pullup']::text[]),
  ('ring-pull-up', 'Ring Pull-Up', 'back', array['biceps', 'forearms']::text[], array['ring pullup']::text[]),
  ('assisted-pull-up-machine', 'Assisted Pull-Up Machine', 'back', array['biceps', 'forearms']::text[], array['assisted pullup machine']::text[]),
  ('band-assisted-pull-up', 'Band-Assisted Pull-Up', 'back', array['biceps', 'forearms']::text[], array['band assisted pullup']::text[]),
  ('assisted-chin-up-machine', 'Assisted Chin-Up Machine', 'back', array['biceps', 'forearms']::text[], array['assisted chinup machine']::text[]),
  ('scapular-pull-up', 'Scapular Pull-Up', 'back', array['biceps', 'forearms']::text[], array['scapular pullup']::text[]),
  ('rope-climb', 'Rope Climb', 'back', array['biceps', 'forearms']::text[], '{}'::text[]),
  ('lat-pulldown', 'Lat Pulldown', 'back', array['biceps', 'forearms']::text[], array['pulldown']::text[]),
  ('wide-grip-lat-pulldown', 'Wide-Grip Lat Pulldown', 'back', array['biceps', 'forearms']::text[], array['wide grip pulldown']::text[]),
  ('close-grip-lat-pulldown', 'Close-Grip Lat Pulldown', 'back', array['biceps', 'forearms']::text[], array['close grip pulldown']::text[]),
  ('neutral-grip-lat-pulldown', 'Neutral-Grip Lat Pulldown', 'back', array['biceps', 'forearms']::text[], array['neutral grip pulldown']::text[]),
  ('reverse-grip-lat-pulldown', 'Reverse-Grip Lat Pulldown', 'back', array['biceps', 'forearms']::text[], array['reverse grip pulldown']::text[]),
  ('v-bar-lat-pulldown', 'V-Bar Lat Pulldown', 'back', array['biceps', 'forearms']::text[], array['v bar pulldown']::text[]),
  ('single-arm-lat-pulldown', 'Single-Arm Lat Pulldown', 'back', array['biceps', 'forearms']::text[], array['single arm pulldown']::text[]),
  ('half-kneeling-single-arm-lat-pulldown', 'Half-Kneeling Single-Arm Lat Pulldown', 'back', array['biceps', 'forearms']::text[], array['half kneeling single arm pulldown']::text[]),
  ('kneeling-lat-pulldown', 'Kneeling Lat Pulldown', 'back', array['biceps', 'forearms']::text[], array['kneeling pulldown']::text[]),
  ('behind-the-neck-pulldown', 'Behind-the-Neck Pulldown', 'back', array['biceps', 'forearms']::text[], '{}'::text[]),
  ('cross-body-lat-pulldown', 'Cross-Body Lat Pulldown', 'back', array['biceps', 'forearms']::text[], array['cross body pulldown']::text[]),
  ('machine-pulldown', 'Machine Pulldown', 'back', array['biceps', 'forearms']::text[], '{}'::text[]),
  ('iso-lateral-pulldown', 'Iso-Lateral Pulldown', 'back', array['biceps', 'forearms']::text[], '{}'::text[]),
  ('bb-bent-over-row', 'BB Bent-Over Row', 'back', array['biceps', 'traps', 'forearms']::text[], array['barbell bent over row']::text[]),
  ('pendlay-row', 'Pendlay Row', 'back', array['biceps', 'traps', 'forearms']::text[], '{}'::text[]),
  ('underhand-bb-row', 'Underhand BB Row', 'back', array['biceps', 'traps', 'forearms']::text[], array['underhand barbell row']::text[]),
  ('wide-grip-bb-row', 'Wide-Grip BB Row', 'back', array['biceps', 'traps', 'forearms']::text[], array['wide grip barbell row']::text[]),
  ('snatch-grip-bb-row', 'Snatch-Grip BB Row', 'back', array['biceps', 'traps', 'forearms']::text[], array['snatch grip barbell row']::text[]),
  ('yates-row', 'Yates Row', 'back', array['biceps', 'traps', 'forearms']::text[], '{}'::text[]),
  ('meadows-row', 'Meadows Row', 'back', array['biceps', 'traps', 'forearms']::text[], '{}'::text[]),
  ('landmine-row', 'Landmine Row', 'back', array['biceps', 'traps', 'forearms']::text[], '{}'::text[]),
  ('single-arm-landmine-row', 'Single-Arm Landmine Row', 'back', array['biceps', 'traps', 'forearms']::text[], '{}'::text[]),
  ('t-bar-row', 'T-Bar Row', 'back', array['biceps', 'traps', 'forearms']::text[], '{}'::text[]),
  ('chest-supported-t-bar-row', 'Chest-Supported T-Bar Row', 'back', array['biceps', 'traps', 'forearms']::text[], '{}'::text[]),
  ('seal-row', 'Seal Row', 'back', array['biceps', 'traps', 'forearms']::text[], '{}'::text[]),
  ('prone-incline-bb-row', 'Prone Incline BB Row', 'back', array['biceps', 'traps', 'forearms']::text[], array['prone incline barbell row']::text[]),
  ('sm-bent-over-row', 'SM Bent-Over Row', 'back', array['biceps', 'traps', 'forearms']::text[], array['smith bent over row']::text[]),
  ('single-arm-db-row', 'Single-Arm DB Row', 'back', array['biceps', 'traps', 'forearms']::text[], array['single arm dumbbell row']::text[]),
  ('two-arm-db-row', 'Two-Arm DB Row', 'back', array['biceps', 'traps', 'forearms']::text[], array['two arm dumbbell row']::text[]),
  ('chest-supported-db-row', 'Chest-Supported DB Row', 'back', array['biceps', 'traps', 'forearms']::text[], array['chest supported dumbbell row']::text[]),
  ('incline-db-row', 'Incline DB Row', 'back', array['biceps', 'traps', 'forearms']::text[], array['incline dumbbell row']::text[]),
  ('db-seal-row', 'DB Seal Row', 'back', array['biceps', 'traps', 'forearms']::text[], array['dumbbell seal row']::text[]),
  ('dead-stop-db-row', 'Dead-Stop DB Row', 'back', array['biceps', 'traps', 'forearms']::text[], array['dead stop dumbbell row']::text[]),
  ('kroc-row', 'Kroc Row', 'back', array['biceps', 'traps', 'forearms']::text[], '{}'::text[]),
  ('renegade-row', 'Renegade Row', 'back', array['biceps', 'traps', 'forearms']::text[], '{}'::text[]),
  ('gorilla-row', 'Gorilla Row', 'back', array['biceps', 'traps', 'forearms']::text[], '{}'::text[]),
  ('single-arm-kb-row', 'Single-Arm KB Row', 'back', array['biceps', 'traps', 'forearms']::text[], array['single arm kettlebell row']::text[]),
  ('batwing-row', 'Batwing Row', 'back', array['biceps', 'traps', 'forearms']::text[], '{}'::text[]),
  ('seated-cable-row', 'Seated Cable Row', 'back', array['biceps', 'traps']::text[], '{}'::text[]),
  ('wide-grip-seated-cable-row', 'Wide-Grip Seated Cable Row', 'back', array['biceps', 'traps']::text[], '{}'::text[]),
  ('close-grip-seated-cable-row', 'Close-Grip Seated Cable Row', 'back', array['biceps', 'traps']::text[], '{}'::text[]),
  ('rope-seated-cable-row', 'Rope Seated Cable Row', 'back', array['biceps', 'traps']::text[], '{}'::text[]),
  ('single-arm-cable-row', 'Single-Arm Cable Row', 'back', array['biceps', 'traps']::text[], '{}'::text[]),
  ('standing-cable-row', 'Standing Cable Row', 'back', array['biceps', 'traps']::text[], '{}'::text[]),
  ('machine-row', 'Machine Row', 'back', array['biceps', 'traps']::text[], '{}'::text[]),
  ('iso-lateral-machine-row', 'Iso-Lateral Machine Row', 'back', array['biceps', 'traps']::text[], '{}'::text[]),
  ('chest-supported-machine-row', 'Chest-Supported Machine Row', 'back', array['biceps', 'traps']::text[], '{}'::text[]),
  ('plate-loaded-row', 'Plate-Loaded Row', 'back', array['biceps', 'traps']::text[], '{}'::text[]),
  ('low-row-machine', 'Low Row Machine', 'back', array['biceps', 'traps']::text[], '{}'::text[]),
  ('high-row-machine', 'High Row Machine', 'back', array['biceps', 'traps']::text[], '{}'::text[]),
  ('iso-lateral-high-row', 'Iso-Lateral High Row', 'back', array['biceps', 'traps']::text[], '{}'::text[]),
  ('iso-lateral-low-row', 'Iso-Lateral Low Row', 'back', array['biceps', 'traps']::text[], '{}'::text[]),
  ('sled-row', 'Sled Row', 'back', array['biceps', 'traps']::text[], '{}'::text[]),
  ('straight-arm-cable-pulldown', 'Straight-Arm Cable Pulldown', 'back', array['triceps', 'core']::text[], '{}'::text[]),
  ('rope-straight-arm-pulldown', 'Rope Straight-Arm Pulldown', 'back', array['triceps', 'core']::text[], '{}'::text[]),
  ('machine-pullover', 'Machine Pullover', 'back', array['triceps', 'core']::text[], '{}'::text[]),
  ('conventional-deadlift', 'Conventional Deadlift', 'back', array['hamstrings', 'glutes', 'traps', 'forearms']::text[], '{}'::text[]),
  ('sumo-deadlift', 'Sumo Deadlift', 'back', array['hamstrings', 'glutes', 'traps', 'forearms']::text[], '{}'::text[]),
  ('trap-bar-deadlift', 'Trap Bar Deadlift', 'back', array['hamstrings', 'glutes', 'traps', 'forearms']::text[], '{}'::text[]),
  ('deficit-deadlift', 'Deficit Deadlift', 'back', array['hamstrings', 'glutes', 'traps', 'forearms']::text[], '{}'::text[]),
  ('rack-pull', 'Rack Pull', 'back', array['hamstrings', 'glutes', 'traps', 'forearms']::text[], '{}'::text[]),
  ('block-pull', 'Block Pull', 'back', array['hamstrings', 'glutes', 'traps', 'forearms']::text[], '{}'::text[]),
  ('snatch-grip-deadlift', 'Snatch-Grip Deadlift', 'back', array['hamstrings', 'glutes', 'traps', 'forearms']::text[], '{}'::text[]),
  ('paused-deadlift', 'Paused Deadlift', 'back', array['hamstrings', 'glutes', 'traps', 'forearms']::text[], '{}'::text[]),
  ('banded-deadlift', 'Banded Deadlift', 'back', array['hamstrings', 'glutes', 'traps', 'forearms']::text[], '{}'::text[]),
  ('back-extension', 'Back Extension', 'back', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('45-degree-back-extension', '45-Degree Back Extension', 'back', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('weighted-back-extension', 'Weighted Back Extension', 'back', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('reverse-hyperextension', 'Reverse Hyperextension', 'back', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('machine-back-extension', 'Machine Back Extension', 'back', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('jefferson-curl', 'Jefferson Curl', 'back', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('superman', 'Superman', 'back', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('inverted-row', 'Inverted Row', 'back', array['biceps', 'core', 'forearms']::text[], '{}'::text[]),
  ('feet-elevated-inverted-row', 'Feet-Elevated Inverted Row', 'back', array['biceps', 'core', 'forearms']::text[], '{}'::text[]),
  ('ring-row', 'Ring Row', 'back', array['biceps', 'core', 'forearms']::text[], '{}'::text[]),
  ('suspension-row', 'Suspension Row', 'back', array['biceps', 'core', 'forearms']::text[], '{}'::text[]),
  ('standing-bb-overhead-press', 'Standing BB Overhead Press', 'shoulders', array['triceps', 'traps', 'core']::text[], array['standing barbell overhead press', 'standing bb ohp', 'standing barbell ohp']::text[]),
  ('seated-bb-overhead-press', 'Seated BB Overhead Press', 'shoulders', array['triceps', 'traps', 'core']::text[], array['seated barbell overhead press', 'seated bb ohp', 'seated barbell ohp']::text[]),
  ('kneeling-bb-overhead-press', 'Kneeling BB Overhead Press', 'shoulders', array['triceps', 'traps', 'core']::text[], array['kneeling barbell overhead press', 'kneeling bb ohp', 'kneeling barbell ohp']::text[]),
  ('push-press', 'Push Press', 'shoulders', array['triceps', 'traps', 'core']::text[], '{}'::text[]),
  ('behind-the-neck-press', 'Behind-the-Neck Press', 'shoulders', array['triceps', 'traps', 'core']::text[], '{}'::text[]),
  ('behind-the-neck-push-press', 'Behind-the-Neck Push Press', 'shoulders', array['triceps', 'traps', 'core']::text[], '{}'::text[]),
  ('bb-z-press', 'BB Z Press', 'shoulders', array['triceps', 'traps', 'core']::text[], array['barbell z press']::text[]),
  ('overhead-pin-press', 'Overhead Pin Press', 'shoulders', array['triceps', 'traps', 'core']::text[], '{}'::text[]),
  ('savickas-press', 'Savickas Press', 'shoulders', array['triceps', 'traps', 'core']::text[], '{}'::text[]),
  ('bradford-press', 'Bradford Press', 'shoulders', array['triceps', 'traps', 'core']::text[], '{}'::text[]),
  ('log-press', 'Log Press', 'shoulders', array['triceps', 'traps', 'core']::text[], '{}'::text[]),
  ('axle-overhead-press', 'Axle Overhead Press', 'shoulders', array['triceps', 'traps', 'core']::text[], array['axle ohp']::text[]),
  ('viking-press', 'Viking Press', 'shoulders', array['triceps', 'traps', 'core']::text[], '{}'::text[]),
  ('seated-db-shoulder-press', 'Seated DB Shoulder Press', 'shoulders', array['triceps', 'traps']::text[], array['seated dumbbell shoulder press']::text[]),
  ('standing-db-shoulder-press', 'Standing DB Shoulder Press', 'shoulders', array['triceps', 'traps']::text[], array['standing dumbbell shoulder press']::text[]),
  ('incline-db-shoulder-press', 'Incline DB Shoulder Press', 'shoulders', array['triceps', 'traps']::text[], array['incline dumbbell shoulder press']::text[]),
  ('neutral-grip-db-shoulder-press', 'Neutral-Grip DB Shoulder Press', 'shoulders', array['triceps', 'traps']::text[], array['neutral grip dumbbell shoulder press']::text[]),
  ('single-arm-db-shoulder-press', 'Single-Arm DB Shoulder Press', 'shoulders', array['triceps', 'traps']::text[], array['single arm dumbbell shoulder press']::text[]),
  ('half-kneeling-db-overhead-press', 'Half-Kneeling DB Overhead Press', 'shoulders', array['triceps', 'traps']::text[], array['half kneeling dumbbell overhead press', 'half kneeling db ohp', 'half kneeling dumbbell ohp']::text[]),
  ('single-arm-db-push-press', 'Single-Arm DB Push Press', 'shoulders', array['triceps', 'traps']::text[], array['single arm dumbbell push press']::text[]),
  ('arnold-press', 'Arnold Press', 'shoulders', array['triceps', 'traps']::text[], '{}'::text[]),
  ('seated-arnold-press', 'Seated Arnold Press', 'shoulders', array['triceps', 'traps']::text[], '{}'::text[]),
  ('db-z-press', 'DB Z Press', 'shoulders', array['triceps', 'traps']::text[], array['dumbbell z press']::text[]),
  ('circus-db-press', 'Circus DB Press', 'shoulders', array['triceps', 'traps']::text[], array['circus dumbbell press']::text[]),
  ('kb-overhead-press', 'KB Overhead Press', 'shoulders', array['triceps', 'traps']::text[], array['kettlebell overhead press', 'kb ohp', 'kettlebell ohp']::text[]),
  ('bottoms-up-kb-press', 'Bottoms-Up KB Press', 'shoulders', array['triceps', 'traps']::text[], array['bottoms up kettlebell press']::text[]),
  ('double-kb-press', 'Double KB Press', 'shoulders', array['triceps', 'traps']::text[], array['double kettlebell press']::text[]),
  ('tall-kneeling-kb-press', 'Tall-Kneeling KB Press', 'shoulders', array['triceps', 'traps']::text[], array['tall kneeling kettlebell press']::text[]),
  ('sm-shoulder-press', 'SM Shoulder Press', 'shoulders', array['triceps', 'traps']::text[], array['smith shoulder press']::text[]),
  ('machine-shoulder-press', 'Machine Shoulder Press', 'shoulders', array['triceps', 'traps']::text[], '{}'::text[]),
  ('iso-lateral-shoulder-press', 'Iso-Lateral Shoulder Press', 'shoulders', array['triceps', 'traps']::text[], '{}'::text[]),
  ('plate-loaded-shoulder-press', 'Plate-Loaded Shoulder Press', 'shoulders', array['triceps', 'traps']::text[], '{}'::text[]),
  ('standing-cable-overhead-press', 'Standing Cable Overhead Press', 'shoulders', array['triceps', 'traps']::text[], array['standing cable ohp']::text[]),
  ('half-kneeling-cable-press', 'Half-Kneeling Cable Press', 'shoulders', array['triceps', 'traps']::text[], '{}'::text[]),
  ('landmine-shoulder-press', 'Landmine Shoulder Press', 'shoulders', array['triceps', 'traps']::text[], '{}'::text[]),
  ('single-arm-landmine-press', 'Single-Arm Landmine Press', 'shoulders', array['triceps', 'traps']::text[], '{}'::text[]),
  ('handstand-push-up', 'Handstand Push-Up', 'shoulders', array['triceps', 'core']::text[], array['handstand pushup']::text[]),
  ('pike-push-up', 'Pike Push-Up', 'shoulders', array['triceps', 'core']::text[], array['pike pushup']::text[]),
  ('db-lateral-raise', 'DB Lateral Raise', 'shoulders', array['traps']::text[], array['dumbbell lateral raise']::text[]),
  ('seated-db-lateral-raise', 'Seated DB Lateral Raise', 'shoulders', array['traps']::text[], array['seated dumbbell lateral raise']::text[]),
  ('incline-db-lateral-raise', 'Incline DB Lateral Raise', 'shoulders', array['traps']::text[], array['incline dumbbell lateral raise']::text[]),
  ('partial-db-lateral-raise', 'Partial DB Lateral Raise', 'shoulders', array['traps']::text[], array['partial dumbbell lateral raise']::text[]),
  ('dead-stop-db-lateral-raise', 'Dead-Stop DB Lateral Raise', 'shoulders', array['traps']::text[], array['dead stop dumbbell lateral raise']::text[]),
  ('cable-lateral-raise', 'Cable Lateral Raise', 'shoulders', array['traps']::text[], '{}'::text[]),
  ('single-arm-cable-lateral-raise', 'Single-Arm Cable Lateral Raise', 'shoulders', array['traps']::text[], '{}'::text[]),
  ('behind-the-back-cable-lateral-raise', 'Behind-the-Back Cable Lateral Raise', 'shoulders', array['traps']::text[], '{}'::text[]),
  ('leaning-cable-lateral-raise', 'Leaning Cable Lateral Raise', 'shoulders', array['traps']::text[], '{}'::text[]),
  ('machine-lateral-raise', 'Machine Lateral Raise', 'shoulders', array['traps']::text[], '{}'::text[]),
  ('seated-machine-lateral-raise', 'Seated Machine Lateral Raise', 'shoulders', array['traps']::text[], '{}'::text[]),
  ('banded-lateral-raise', 'Banded Lateral Raise', 'shoulders', array['traps']::text[], '{}'::text[]),
  ('landmine-lateral-raise', 'Landmine Lateral Raise', 'shoulders', array['traps']::text[], '{}'::text[]),
  ('lu-raise', 'Lu Raise', 'shoulders', array['traps']::text[], '{}'::text[]),
  ('db-scaption', 'DB Scaption', 'shoulders', array['traps']::text[], array['dumbbell scaption']::text[]),
  ('db-6-way-raise', 'DB 6-Way Raise', 'shoulders', array['traps']::text[], array['dumbbell 6 way raise']::text[]),
  ('bus-driver', 'Bus Driver', 'shoulders', array['traps']::text[], '{}'::text[]),
  ('db-front-raise', 'DB Front Raise', 'shoulders', array['chest']::text[], array['dumbbell front raise']::text[]),
  ('bb-front-raise', 'BB Front Raise', 'shoulders', array['chest']::text[], array['barbell front raise']::text[]),
  ('plate-front-raise', 'Plate Front Raise', 'shoulders', array['chest']::text[], '{}'::text[]),
  ('cable-front-raise', 'Cable Front Raise', 'shoulders', array['chest']::text[], '{}'::text[]),
  ('rope-front-raise', 'Rope Front Raise', 'shoulders', array['chest']::text[], '{}'::text[]),
  ('incline-db-front-raise', 'Incline DB Front Raise', 'shoulders', array['chest']::text[], array['incline dumbbell front raise']::text[]),
  ('db-rear-delt-fly', 'DB Rear Delt Fly', 'shoulders', array['traps', 'back']::text[], array['dumbbell rear delt fly', 'db reardelt fly', 'dumbbell reardelt fly']::text[]),
  ('seated-db-rear-delt-fly', 'Seated DB Rear Delt Fly', 'shoulders', array['traps', 'back']::text[], array['seated dumbbell rear delt fly', 'seated db reardelt fly', 'seated dumbbell reardelt fly']::text[]),
  ('chest-supported-rear-delt-fly', 'Chest-Supported Rear Delt Fly', 'shoulders', array['traps', 'back']::text[], array['chest supported reardelt fly']::text[]),
  ('reverse-pec-deck', 'Reverse Pec Deck', 'shoulders', array['traps', 'back']::text[], '{}'::text[]),
  ('cable-rear-delt-fly', 'Cable Rear Delt Fly', 'shoulders', array['traps', 'back']::text[], array['cable reardelt fly']::text[]),
  ('single-arm-cable-rear-delt-fly', 'Single-Arm Cable Rear Delt Fly', 'shoulders', array['traps', 'back']::text[], array['single arm cable reardelt fly']::text[]),
  ('cable-crossover-rear-delt-fly', 'Cable Crossover Rear Delt Fly', 'shoulders', array['traps', 'back']::text[], array['cable crossover reardelt fly']::text[]),
  ('cable-rear-delt-row', 'Cable Rear Delt Row', 'shoulders', array['traps', 'back']::text[], array['cable reardelt row']::text[]),
  ('wide-grip-bb-high-row', 'Wide-Grip BB High Row', 'shoulders', array['traps', 'back']::text[], array['wide grip barbell high row']::text[]),
  ('cable-face-pull', 'Cable Face Pull', 'shoulders', array['traps', 'back']::text[], '{}'::text[]),
  ('band-face-pull', 'Band Face Pull', 'shoulders', array['traps', 'back']::text[], '{}'::text[]),
  ('band-pull-apart', 'Band Pull-Apart', 'shoulders', array['traps', 'back']::text[], '{}'::text[]),
  ('prone-y-raise', 'Prone Y Raise', 'shoulders', array['traps', 'back']::text[], '{}'::text[]),
  ('prone-t-raise', 'Prone T Raise', 'shoulders', array['traps', 'back']::text[], '{}'::text[]),
  ('prone-w-raise', 'Prone W Raise', 'shoulders', array['traps', 'back']::text[], '{}'::text[]),
  ('cable-y-raise', 'Cable Y-Raise', 'shoulders', array['traps', 'back']::text[], '{}'::text[]),
  ('cable-external-rotation', 'Cable External Rotation', 'shoulders', array['traps', 'core']::text[], '{}'::text[]),
  ('db-external-rotation', 'DB External Rotation', 'shoulders', array['traps', 'core']::text[], array['dumbbell external rotation']::text[]),
  ('band-external-rotation', 'Band External Rotation', 'shoulders', array['traps', 'core']::text[], '{}'::text[]),
  ('cable-internal-rotation', 'Cable Internal Rotation', 'shoulders', array['traps', 'core']::text[], '{}'::text[]),
  ('cuban-press', 'Cuban Press', 'shoulders', array['traps', 'core']::text[], '{}'::text[]),
  ('kb-halo', 'KB Halo', 'shoulders', array['traps', 'core']::text[], array['kettlebell halo']::text[]),
  ('wall-slide', 'Wall Slide', 'shoulders', array['traps', 'core']::text[], '{}'::text[]),
  ('band-shoulder-dislocate', 'Band Shoulder Dislocate', 'shoulders', array['traps', 'core']::text[], '{}'::text[]),
  ('overhead-carry', 'Overhead Carry', 'shoulders', array['traps', 'core']::text[], '{}'::text[]),
  ('waiter-walk', 'Waiter Walk', 'shoulders', array['traps', 'core']::text[], '{}'::text[]),
  ('bottoms-up-kb-carry', 'Bottoms-Up KB Carry', 'shoulders', array['traps', 'core']::text[], array['bottoms up kettlebell carry']::text[]),
  ('bb-shrug', 'BB Shrug', 'traps', array['forearms', 'shoulders']::text[], array['barbell shrug']::text[]),
  ('behind-the-back-bb-shrug', 'Behind-the-Back BB Shrug', 'traps', array['forearms', 'shoulders']::text[], array['behind the back barbell shrug']::text[]),
  ('db-shrug', 'DB Shrug', 'traps', array['forearms', 'shoulders']::text[], array['dumbbell shrug']::text[]),
  ('seated-db-shrug', 'Seated DB Shrug', 'traps', array['forearms', 'shoulders']::text[], array['seated dumbbell shrug']::text[]),
  ('incline-db-shrug', 'Incline DB Shrug', 'traps', array['forearms', 'shoulders']::text[], array['incline dumbbell shrug']::text[]),
  ('sm-shrug', 'SM Shrug', 'traps', array['forearms', 'shoulders']::text[], array['smith shrug']::text[]),
  ('trap-bar-shrug', 'Trap Bar Shrug', 'traps', array['forearms', 'shoulders']::text[], '{}'::text[]),
  ('cable-shrug', 'Cable Shrug', 'traps', array['forearms', 'shoulders']::text[], '{}'::text[]),
  ('rope-cable-shrug', 'Rope Cable Shrug', 'traps', array['forearms', 'shoulders']::text[], '{}'::text[]),
  ('machine-shrug', 'Machine Shrug', 'traps', array['forearms', 'shoulders']::text[], '{}'::text[]),
  ('plate-loaded-shrug', 'Plate-Loaded Shrug', 'traps', array['forearms', 'shoulders']::text[], '{}'::text[]),
  ('snatch-grip-shrug', 'Snatch-Grip Shrug', 'traps', array['forearms', 'shoulders']::text[], '{}'::text[]),
  ('overhead-shrug', 'Overhead Shrug', 'traps', array['forearms', 'shoulders']::text[], '{}'::text[]),
  ('paused-bb-shrug', 'Paused BB Shrug', 'traps', array['forearms', 'shoulders']::text[], array['paused barbell shrug']::text[]),
  ('kirk-shrug', 'Kirk Shrug', 'traps', array['forearms', 'shoulders']::text[], '{}'::text[]),
  ('band-shrug', 'Band Shrug', 'traps', array['forearms', 'shoulders']::text[], '{}'::text[]),
  ('seated-cable-shrug', 'Seated Cable Shrug', 'traps', array['forearms', 'shoulders']::text[], '{}'::text[]),
  ('chest-supported-shrug', 'Chest-Supported Shrug', 'traps', array['forearms', 'shoulders']::text[], '{}'::text[]),
  ('prone-incline-shrug', 'Prone Incline Shrug', 'traps', array['forearms', 'shoulders']::text[], '{}'::text[]),
  ('bent-over-shrug', 'Bent-Over Shrug', 'traps', array['forearms', 'shoulders']::text[], '{}'::text[]),
  ('landmine-shrug', 'Landmine Shrug', 'traps', array['forearms', 'shoulders']::text[], '{}'::text[]),
  ('rack-pull-shrug', 'Rack Pull Shrug', 'traps', array['forearms', 'shoulders']::text[], '{}'::text[]),
  ('bb-upright-row', 'BB Upright Row', 'traps', array['shoulders', 'biceps']::text[], array['barbell upright row']::text[]),
  ('wide-grip-bb-upright-row', 'Wide-Grip BB Upright Row', 'traps', array['shoulders', 'biceps']::text[], array['wide grip barbell upright row']::text[]),
  ('db-upright-row', 'DB Upright Row', 'traps', array['shoulders', 'biceps']::text[], array['dumbbell upright row']::text[]),
  ('cable-upright-row', 'Cable Upright Row', 'traps', array['shoulders', 'biceps']::text[], '{}'::text[]),
  ('rope-upright-row', 'Rope Upright Row', 'traps', array['shoulders', 'biceps']::text[], '{}'::text[]),
  ('sm-upright-row', 'SM Upright Row', 'traps', array['shoulders', 'biceps']::text[], array['smith upright row']::text[]),
  ('kb-upright-row', 'KB Upright Row', 'traps', array['shoulders', 'biceps']::text[], array['kettlebell upright row']::text[]),
  ('high-pull', 'High Pull', 'traps', array['shoulders', 'biceps']::text[], '{}'::text[]),
  ('bb-high-pull', 'BB High Pull', 'traps', array['shoulders', 'biceps']::text[], array['barbell high pull']::text[]),
  ('db-high-pull', 'DB High Pull', 'traps', array['shoulders', 'biceps']::text[], array['dumbbell high pull']::text[]),
  ('snatch-grip-high-pull', 'Snatch-Grip High Pull', 'traps', array['shoulders', 'biceps']::text[], '{}'::text[]),
  ('y-raise', 'Y-Raise', 'traps', array['shoulders', 'back']::text[], '{}'::text[]),
  ('incline-y-raise', 'Incline Y-Raise', 'traps', array['shoulders', 'back']::text[], '{}'::text[]),
  ('prone-trap-raise', 'Prone Trap Raise', 'traps', array['shoulders', 'back']::text[], '{}'::text[]),
  ('cable-trap-3-raise', 'Cable Trap-3 Raise', 'traps', array['shoulders', 'back']::text[], '{}'::text[]),
  ('scapular-shrug', 'Scapular Shrug', 'traps', array['shoulders', 'back']::text[], '{}'::text[]),
  ('powell-raise', 'Powell Raise', 'traps', array['shoulders', 'back']::text[], '{}'::text[]),
  ('farmer-s-carry', 'Farmer''s Carry', 'traps', array['forearms', 'core']::text[], '{}'::text[]),
  ('trap-bar-carry', 'Trap Bar Carry', 'traps', array['forearms', 'core']::text[], '{}'::text[]),
  ('suitcase-carry', 'Suitcase Carry', 'traps', array['forearms', 'core']::text[], '{}'::text[]),
  ('heavy-db-hold', 'Heavy DB Hold', 'traps', array['forearms', 'core']::text[], array['heavy dumbbell hold']::text[]),
  ('zercher-carry', 'Zercher Carry', 'traps', array['forearms', 'core']::text[], '{}'::text[]),
  ('yoke-walk', 'Yoke Walk', 'traps', array['forearms', 'core']::text[], '{}'::text[]),
  ('bb-curl', 'BB Curl', 'biceps', array['forearms']::text[], array['barbell curl']::text[]),
  ('ez-bar-curl', 'EZ-Bar Curl', 'biceps', array['forearms']::text[], '{}'::text[]),
  ('wide-grip-bb-curl', 'Wide-Grip BB Curl', 'biceps', array['forearms']::text[], array['wide grip barbell curl']::text[]),
  ('close-grip-bb-curl', 'Close-Grip BB Curl', 'biceps', array['forearms']::text[], array['close grip barbell curl']::text[]),
  ('cheat-curl', 'Cheat Curl', 'biceps', array['forearms']::text[], '{}'::text[]),
  ('strict-curl', 'Strict Curl', 'biceps', array['forearms']::text[], '{}'::text[]),
  ('reverse-bb-curl', 'Reverse BB Curl', 'biceps', array['forearms']::text[], array['reverse barbell curl']::text[]),
  ('drag-curl', 'Drag Curl', 'biceps', array['forearms']::text[], '{}'::text[]),
  ('21s', '21s', 'biceps', array['forearms']::text[], '{}'::text[]),
  ('bb-preacher-curl', 'BB Preacher Curl', 'biceps', array['forearms']::text[], array['barbell preacher curl']::text[]),
  ('ez-bar-preacher-curl', 'EZ-Bar Preacher Curl', 'biceps', array['forearms']::text[], '{}'::text[]),
  ('sm-drag-curl', 'SM Drag Curl', 'biceps', array['forearms']::text[], array['smith drag curl']::text[]),
  ('db-curl', 'DB Curl', 'biceps', array['forearms']::text[], array['dumbbell curl']::text[]),
  ('alternating-db-curl', 'Alternating DB Curl', 'biceps', array['forearms']::text[], array['alternating dumbbell curl']::text[]),
  ('seated-db-curl', 'Seated DB Curl', 'biceps', array['forearms']::text[], array['seated dumbbell curl']::text[]),
  ('standing-db-curl', 'Standing DB Curl', 'biceps', array['forearms']::text[], array['standing dumbbell curl']::text[]),
  ('incline-db-curl', 'Incline DB Curl', 'biceps', array['forearms']::text[], array['incline dumbbell curl']::text[]),
  ('spider-curl', 'Spider Curl', 'biceps', array['forearms']::text[], '{}'::text[]),
  ('db-preacher-curl', 'DB Preacher Curl', 'biceps', array['forearms']::text[], array['dumbbell preacher curl']::text[]),
  ('concentration-curl', 'Concentration Curl', 'biceps', array['forearms']::text[], '{}'::text[]),
  ('hammer-curl', 'Hammer Curl', 'biceps', array['forearms']::text[], '{}'::text[]),
  ('incline-hammer-curl', 'Incline Hammer Curl', 'biceps', array['forearms']::text[], '{}'::text[]),
  ('cross-body-hammer-curl', 'Cross-Body Hammer Curl', 'biceps', array['forearms']::text[], '{}'::text[]),
  ('zottman-curl', 'Zottman Curl', 'biceps', array['forearms']::text[], '{}'::text[]),
  ('waiter-curl', 'Waiter Curl', 'biceps', array['forearms']::text[], '{}'::text[]),
  ('db-reverse-curl', 'DB Reverse Curl', 'biceps', array['forearms']::text[], array['dumbbell reverse curl']::text[]),
  ('prone-incline-db-curl', 'Prone Incline DB Curl', 'biceps', array['forearms']::text[], array['prone incline dumbbell curl']::text[]),
  ('kneeling-db-curl', 'Kneeling DB Curl', 'biceps', array['forearms']::text[], array['kneeling dumbbell curl']::text[]),
  ('cable-curl', 'Cable Curl', 'biceps', array['forearms']::text[], '{}'::text[]),
  ('rope-hammer-curl', 'Rope Hammer Curl', 'biceps', array['forearms']::text[], '{}'::text[]),
  ('bayesian-cable-curl', 'Bayesian Cable Curl', 'biceps', array['forearms']::text[], '{}'::text[]),
  ('high-cable-curl', 'High Cable Curl', 'biceps', array['forearms']::text[], '{}'::text[]),
  ('single-arm-cable-curl', 'Single-Arm Cable Curl', 'biceps', array['forearms']::text[], '{}'::text[]),
  ('cable-preacher-curl', 'Cable Preacher Curl', 'biceps', array['forearms']::text[], '{}'::text[]),
  ('cable-reverse-curl', 'Cable Reverse Curl', 'biceps', array['forearms']::text[], '{}'::text[]),
  ('ez-bar-cable-curl', 'EZ-Bar Cable Curl', 'biceps', array['forearms']::text[], '{}'::text[]),
  ('overhead-cable-curl', 'Overhead Cable Curl', 'biceps', array['forearms']::text[], '{}'::text[]),
  ('lying-cable-curl', 'Lying Cable Curl', 'biceps', array['forearms']::text[], '{}'::text[]),
  ('machine-preacher-curl', 'Machine Preacher Curl', 'biceps', array['forearms', 'back']::text[], '{}'::text[]),
  ('machine-bicep-curl', 'Machine Bicep Curl', 'biceps', array['forearms', 'back']::text[], '{}'::text[]),
  ('plate-loaded-preacher-curl', 'Plate-Loaded Preacher Curl', 'biceps', array['forearms', 'back']::text[], '{}'::text[]),
  ('band-curl', 'Band Curl', 'biceps', array['forearms', 'back']::text[], '{}'::text[]),
  ('chin-up-hold', 'Chin-Up Hold', 'biceps', array['forearms', 'back']::text[], array['chinup hold']::text[]),
  ('bodyweight-bicep-curl', 'Bodyweight Bicep Curl', 'biceps', array['forearms', 'back']::text[], '{}'::text[]),
  ('ring-curl', 'Ring Curl', 'biceps', array['forearms', 'back']::text[], '{}'::text[]),
  ('kb-curl', 'KB Curl', 'biceps', array['forearms', 'back']::text[], array['kettlebell curl']::text[]),
  ('fat-grip-db-curl', 'Fat-Grip DB Curl', 'biceps', array['forearms', 'back']::text[], array['fat grip dumbbell curl']::text[]),
  ('static-hold-curl', 'Static Hold Curl', 'biceps', array['forearms', 'back']::text[], '{}'::text[]),
  ('close-grip-bb-bench-press', 'Close-Grip BB Bench Press', 'triceps', array['chest', 'shoulders']::text[], array['close grip barbell bench press', 'close grip bb bench', 'close grip barbell bench']::text[]),
  ('close-grip-incline-bb-bench-press', 'Close-Grip Incline BB Bench Press', 'triceps', array['chest', 'shoulders']::text[], array['close grip incline barbell bench press', 'close grip incline bb bench', 'close grip incline barbell bench']::text[]),
  ('close-grip-sm-bench-press', 'Close-Grip SM Bench Press', 'triceps', array['chest', 'shoulders']::text[], array['close grip smith bench press', 'close grip sm bench', 'close grip smith bench']::text[]),
  ('close-grip-db-press', 'Close-Grip DB Press', 'triceps', array['chest', 'shoulders']::text[], array['close grip dumbbell press']::text[]),
  ('bench-dip', 'Bench Dip', 'triceps', array['chest', 'shoulders']::text[], '{}'::text[]),
  ('weighted-bench-dip', 'Weighted Bench Dip', 'triceps', array['chest', 'shoulders']::text[], '{}'::text[]),
  ('triceps-dip', 'Triceps Dip', 'triceps', array['chest', 'shoulders']::text[], '{}'::text[]),
  ('machine-triceps-dip', 'Machine Triceps Dip', 'triceps', array['chest', 'shoulders']::text[], '{}'::text[]),
  ('diamond-push-up', 'Diamond Push-Up', 'triceps', array['chest', 'shoulders']::text[], array['diamond pushup']::text[]),
  ('sphinx-push-up', 'Sphinx Push-Up', 'triceps', array['chest', 'shoulders']::text[], array['sphinx pushup']::text[]),
  ('jm-press', 'JM Press', 'triceps', array['chest', 'shoulders']::text[], '{}'::text[]),
  ('floor-skull-crusher', 'Floor Skull Crusher', 'triceps', array['chest', 'shoulders']::text[], array['floor skullcrusher']::text[]),
  ('ez-bar-skull-crusher', 'EZ-Bar Skull Crusher', 'triceps', array['shoulders']::text[], array['ez bar skullcrusher']::text[]),
  ('bb-skull-crusher', 'BB Skull Crusher', 'triceps', array['shoulders']::text[], array['barbell skull crusher', 'bb skullcrusher', 'barbell skullcrusher']::text[]),
  ('db-skull-crusher', 'DB Skull Crusher', 'triceps', array['shoulders']::text[], array['dumbbell skull crusher', 'db skullcrusher', 'dumbbell skullcrusher']::text[]),
  ('incline-skull-crusher', 'Incline Skull Crusher', 'triceps', array['shoulders']::text[], array['incline skullcrusher']::text[]),
  ('decline-skull-crusher', 'Decline Skull Crusher', 'triceps', array['shoulders']::text[], array['decline skullcrusher']::text[]),
  ('cable-skull-crusher', 'Cable Skull Crusher', 'triceps', array['shoulders']::text[], array['cable skullcrusher']::text[]),
  ('rope-skull-crusher', 'Rope Skull Crusher', 'triceps', array['shoulders']::text[], array['rope skullcrusher']::text[]),
  ('overhead-bb-extension', 'Overhead BB Extension', 'triceps', array['shoulders']::text[], array['overhead barbell extension']::text[]),
  ('overhead-db-extension', 'Overhead DB Extension', 'triceps', array['shoulders']::text[], array['overhead dumbbell extension']::text[]),
  ('single-arm-overhead-db-extension', 'Single-Arm Overhead DB Extension', 'triceps', array['shoulders']::text[], array['single arm overhead dumbbell extension']::text[]),
  ('seated-overhead-db-extension', 'Seated Overhead DB Extension', 'triceps', array['shoulders']::text[], array['seated overhead dumbbell extension']::text[]),
  ('overhead-cable-extension', 'Overhead Cable Extension', 'triceps', array['shoulders']::text[], '{}'::text[]),
  ('rope-overhead-cable-extension', 'Rope Overhead Cable Extension', 'triceps', array['shoulders']::text[], '{}'::text[]),
  ('single-arm-overhead-cable-extension', 'Single-Arm Overhead Cable Extension', 'triceps', array['shoulders']::text[], '{}'::text[]),
  ('kneeling-overhead-cable-extension', 'Kneeling Overhead Cable Extension', 'triceps', array['shoulders']::text[], '{}'::text[]),
  ('cross-body-cable-extension', 'Cross-Body Cable Extension', 'triceps', array['shoulders']::text[], '{}'::text[]),
  ('cable-pushdown', 'Cable Pushdown', 'triceps', '{}'::text[], '{}'::text[]),
  ('rope-pushdown', 'Rope Pushdown', 'triceps', '{}'::text[], '{}'::text[]),
  ('straight-bar-pushdown', 'Straight-Bar Pushdown', 'triceps', '{}'::text[], '{}'::text[]),
  ('v-bar-pushdown', 'V-Bar Pushdown', 'triceps', '{}'::text[], '{}'::text[]),
  ('reverse-grip-pushdown', 'Reverse-Grip Pushdown', 'triceps', '{}'::text[], '{}'::text[]),
  ('single-arm-cable-pushdown', 'Single-Arm Cable Pushdown', 'triceps', '{}'::text[], '{}'::text[]),
  ('machine-triceps-extension', 'Machine Triceps Extension', 'triceps', '{}'::text[], '{}'::text[]),
  ('plate-loaded-triceps-extension', 'Plate-Loaded Triceps Extension', 'triceps', '{}'::text[], '{}'::text[]),
  ('band-pushdown', 'Band Pushdown', 'triceps', '{}'::text[], '{}'::text[]),
  ('db-triceps-kickback', 'DB Triceps Kickback', 'triceps', '{}'::text[], array['dumbbell triceps kickback']::text[]),
  ('bent-over-db-kickback', 'Bent-Over DB Kickback', 'triceps', '{}'::text[], array['bent over dumbbell kickback']::text[]),
  ('cable-triceps-kickback', 'Cable Triceps Kickback', 'triceps', '{}'::text[], '{}'::text[]),
  ('tate-press', 'Tate Press', 'triceps', '{}'::text[], '{}'::text[]),
  ('db-triceps-extension', 'DB Triceps Extension', 'triceps', '{}'::text[], array['dumbbell triceps extension']::text[]),
  ('katana-extension', 'Katana Extension', 'triceps', '{}'::text[], '{}'::text[]),
  ('ring-triceps-extension', 'Ring Triceps Extension', 'triceps', array['chest', 'core']::text[], '{}'::text[]),
  ('bodyweight-skull-crusher', 'Bodyweight Skull Crusher', 'triceps', array['chest', 'core']::text[], array['bodyweight skullcrusher']::text[]),
  ('suspension-triceps-extension', 'Suspension Triceps Extension', 'triceps', array['chest', 'core']::text[], '{}'::text[]),
  ('pin-close-grip-press', 'Pin Close-Grip Press', 'triceps', array['chest', 'core']::text[], '{}'::text[]),
  ('board-close-grip-press', 'Board Close-Grip Press', 'triceps', array['chest', 'core']::text[], '{}'::text[]),
  ('california-press', 'California Press', 'triceps', array['chest', 'core']::text[], '{}'::text[]),
  ('rolling-db-extension', 'Rolling DB Extension', 'triceps', array['chest', 'core']::text[], array['rolling dumbbell extension']::text[]),
  ('bb-wrist-curl', 'BB Wrist Curl', 'forearms', '{}'::text[], array['barbell wrist curl']::text[]),
  ('seated-bb-wrist-curl', 'Seated BB Wrist Curl', 'forearms', '{}'::text[], array['seated barbell wrist curl']::text[]),
  ('db-wrist-curl', 'DB Wrist Curl', 'forearms', '{}'::text[], array['dumbbell wrist curl']::text[]),
  ('behind-the-back-bb-wrist-curl', 'Behind-the-Back BB Wrist Curl', 'forearms', '{}'::text[], array['behind the back barbell wrist curl']::text[]),
  ('cable-wrist-curl', 'Cable Wrist Curl', 'forearms', '{}'::text[], '{}'::text[]),
  ('bb-reverse-wrist-curl', 'BB Reverse Wrist Curl', 'forearms', '{}'::text[], array['barbell reverse wrist curl']::text[]),
  ('db-reverse-wrist-curl', 'DB Reverse Wrist Curl', 'forearms', '{}'::text[], array['dumbbell reverse wrist curl']::text[]),
  ('cable-reverse-wrist-curl', 'Cable Reverse Wrist Curl', 'forearms', '{}'::text[], '{}'::text[]),
  ('machine-wrist-curl', 'Machine Wrist Curl', 'forearms', '{}'::text[], '{}'::text[]),
  ('band-wrist-curl', 'Band Wrist Curl', 'forearms', '{}'::text[], '{}'::text[]),
  ('reverse-curl', 'Reverse Curl', 'forearms', array['biceps']::text[], '{}'::text[]),
  ('ez-bar-reverse-curl', 'EZ-Bar Reverse Curl', 'forearms', array['biceps']::text[], '{}'::text[]),
  ('cable-rope-reverse-curl', 'Cable Rope Reverse Curl', 'forearms', array['biceps']::text[], '{}'::text[]),
  ('hammer-curl-forearm-focus', 'Hammer Curl (Forearm Focus)', 'forearms', array['biceps']::text[], '{}'::text[]),
  ('zottman-reverse-curl', 'Zottman Reverse Curl', 'forearms', array['biceps']::text[], '{}'::text[]),
  ('pronated-db-curl', 'Pronated DB Curl', 'forearms', array['biceps']::text[], array['pronated dumbbell curl']::text[]),
  ('fat-grip-hold', 'Fat-Grip Hold', 'forearms', array['biceps']::text[], '{}'::text[]),
  ('dead-hang', 'Dead Hang', 'forearms', array['traps']::text[], '{}'::text[]),
  ('weighted-dead-hang', 'Weighted Dead Hang', 'forearms', array['traps']::text[], '{}'::text[]),
  ('towel-hang', 'Towel Hang', 'forearms', array['traps']::text[], '{}'::text[]),
  ('plate-pinch', 'Plate Pinch', 'forearms', array['traps']::text[], '{}'::text[]),
  ('plate-pinch-carry', 'Plate Pinch Carry', 'forearms', array['traps']::text[], '{}'::text[]),
  ('farmer-hold', 'Farmer Hold', 'forearms', array['traps']::text[], '{}'::text[]),
  ('captains-of-crush-grip', 'Captains of Crush Grip', 'forearms', array['traps']::text[], '{}'::text[]),
  ('hand-gripper', 'Hand Gripper', 'forearms', array['traps']::text[], '{}'::text[]),
  ('fat-grip-farmer-walk', 'Fat-Grip Farmer Walk', 'forearms', array['traps']::text[], '{}'::text[]),
  ('wrist-roller', 'Wrist Roller', 'forearms', array['traps']::text[], '{}'::text[]),
  ('reverse-wrist-roller', 'Reverse Wrist Roller', 'forearms', array['traps']::text[], '{}'::text[]),
  ('sledgehammer-lever', 'Sledgehammer Lever', 'forearms', array['traps']::text[], '{}'::text[]),
  ('radial-deviation', 'Radial Deviation', 'forearms', array['traps']::text[], '{}'::text[]),
  ('ulnar-deviation', 'Ulnar Deviation', 'forearms', array['traps']::text[], '{}'::text[]),
  ('rice-bucket-dig', 'Rice Bucket Dig', 'forearms', array['traps']::text[], '{}'::text[]),
  ('rubber-band-extension', 'Rubber Band Extension', 'forearms', array['traps']::text[], '{}'::text[]),
  ('finger-extension', 'Finger Extension', 'forearms', array['traps']::text[], '{}'::text[]),
  ('barbell-holds', 'Barbell Holds', 'forearms', array['traps']::text[], array['bb holds']::text[]),
  ('axle-bar-hold', 'Axle Bar Hold', 'forearms', array['traps']::text[], '{}'::text[]),
  ('thick-bar-deadlift-hold', 'Thick Bar Deadlift Hold', 'forearms', array['traps']::text[], '{}'::text[]),
  ('pronation-with-hammer', 'Pronation with Hammer', 'forearms', array['biceps', 'core']::text[], '{}'::text[]),
  ('supination-with-hammer', 'Supination with Hammer', 'forearms', array['biceps', 'core']::text[], '{}'::text[]),
  ('cable-pronation', 'Cable Pronation', 'forearms', array['biceps', 'core']::text[], '{}'::text[]),
  ('cable-supination', 'Cable Supination', 'forearms', array['biceps', 'core']::text[], '{}'::text[]),
  ('back-squat', 'Back Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('high-bar-back-squat', 'High-Bar Back Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('low-bar-back-squat', 'Low-Bar Back Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('front-squat', 'Front Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('paused-back-squat', 'Paused Back Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('paused-front-squat', 'Paused Front Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('box-squat', 'Box Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('tempo-back-squat', 'Tempo Back Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('pin-squat', 'Pin Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('anderson-squat', 'Anderson Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('safety-bar-squat', 'Safety Bar Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('zercher-squat', 'Zercher Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('overhead-squat', 'Overhead Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('banded-back-squat', 'Banded Back Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('chain-back-squat', 'Chain Back Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('wide-stance-back-squat', 'Wide-Stance Back Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('narrow-stance-back-squat', 'Narrow-Stance Back Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('heels-elevated-back-squat', 'Heels-Elevated Back Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('sm-squat', 'SM Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], array['smith squat']::text[]),
  ('sm-front-squat', 'SM Front Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], array['smith front squat']::text[]),
  ('sm-heels-elevated-squat', 'SM Heels-Elevated Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], array['smith heels elevated squat']::text[]),
  ('hack-squat', 'Hack Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('machine-hack-squat', 'Machine Hack Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('reverse-hack-squat', 'Reverse Hack Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('v-squat', 'V-Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('pendulum-squat', 'Pendulum Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('belt-squat', 'Belt Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('landmine-squat', 'Landmine Squat', 'quads', array['glutes', 'hamstrings', 'core']::text[], '{}'::text[]),
  ('goblet-squat', 'Goblet Squat', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('db-squat', 'DB Squat', 'quads', array['glutes', 'core']::text[], array['dumbbell squat']::text[]),
  ('kb-goblet-squat', 'KB Goblet Squat', 'quads', array['glutes', 'core']::text[], array['kettlebell goblet squat']::text[]),
  ('double-kb-front-squat', 'Double KB Front Squat', 'quads', array['glutes', 'core']::text[], array['double kettlebell front squat']::text[]),
  ('db-front-squat', 'DB Front Squat', 'quads', array['glutes', 'core']::text[], array['dumbbell front squat']::text[]),
  ('bodyweight-squat', 'Bodyweight Squat', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('sissy-squat', 'Sissy Squat', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('machine-sissy-squat', 'Machine Sissy Squat', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('cyclist-squat', 'Cyclist Squat', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('wall-sit', 'Wall Sit', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('jump-squat', 'Jump Squat', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('box-jump', 'Box Jump', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('pause-goblet-squat', 'Pause Goblet Squat', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('bulgarian-split-squat', 'Bulgarian Split Squat', 'quads', array['glutes', 'core']::text[], array['bss']::text[]),
  ('db-bulgarian-split-squat', 'DB Bulgarian Split Squat', 'quads', array['glutes', 'core']::text[], array['dumbbell bulgarian split squat', 'db bss', 'dumbbell bss']::text[]),
  ('bb-bulgarian-split-squat', 'BB Bulgarian Split Squat', 'quads', array['glutes', 'core']::text[], array['barbell bulgarian split squat', 'bb bss', 'barbell bss']::text[]),
  ('sm-bulgarian-split-squat', 'SM Bulgarian Split Squat', 'quads', array['glutes', 'core']::text[], array['smith bulgarian split squat', 'sm bss', 'smith bss']::text[]),
  ('split-squat', 'Split Squat', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('db-split-squat', 'DB Split Squat', 'quads', array['glutes', 'core']::text[], array['dumbbell split squat']::text[]),
  ('front-foot-elevated-split-squat', 'Front-Foot-Elevated Split Squat', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('deficit-split-squat', 'Deficit Split Squat', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('leg-press', 'Leg Press', 'quads', array['glutes', 'hamstrings']::text[], '{}'::text[]),
  ('narrow-stance-leg-press', 'Narrow-Stance Leg Press', 'quads', array['glutes', 'hamstrings']::text[], '{}'::text[]),
  ('single-leg-leg-press', 'Single-Leg Leg Press', 'quads', array['glutes', 'hamstrings']::text[], '{}'::text[]),
  ('horizontal-leg-press', 'Horizontal Leg Press', 'quads', array['glutes', 'hamstrings']::text[], '{}'::text[]),
  ('45-degree-leg-press', '45-Degree Leg Press', 'quads', array['glutes', 'hamstrings']::text[], '{}'::text[]),
  ('vertical-leg-press', 'Vertical Leg Press', 'quads', array['glutes', 'hamstrings']::text[], '{}'::text[]),
  ('leg-extension', 'Leg Extension', 'quads', array['glutes', 'hamstrings']::text[], '{}'::text[]),
  ('single-leg-extension', 'Single-Leg Extension', 'quads', array['glutes', 'hamstrings']::text[], '{}'::text[]),
  ('paused-leg-extension', 'Paused Leg Extension', 'quads', array['glutes', 'hamstrings']::text[], '{}'::text[]),
  ('banded-leg-extension', 'Banded Leg Extension', 'quads', array['glutes', 'hamstrings']::text[], '{}'::text[]),
  ('machine-squat', 'Machine Squat', 'quads', array['glutes', 'hamstrings']::text[], '{}'::text[]),
  ('smith-leg-press', 'Smith Leg Press', 'quads', array['glutes', 'hamstrings']::text[], array['sm leg press']::text[]),
  ('walking-lunge', 'Walking Lunge', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('db-walking-lunge', 'DB Walking Lunge', 'quads', array['glutes', 'core']::text[], array['dumbbell walking lunge']::text[]),
  ('bb-walking-lunge', 'BB Walking Lunge', 'quads', array['glutes', 'core']::text[], array['barbell walking lunge']::text[]),
  ('reverse-lunge', 'Reverse Lunge', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('db-reverse-lunge', 'DB Reverse Lunge', 'quads', array['glutes', 'core']::text[], array['dumbbell reverse lunge']::text[]),
  ('bb-reverse-lunge', 'BB Reverse Lunge', 'quads', array['glutes', 'core']::text[], array['barbell reverse lunge']::text[]),
  ('forward-lunge', 'Forward Lunge', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('deficit-reverse-lunge', 'Deficit Reverse Lunge', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('curtsy-lunge', 'Curtsy Lunge', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('lateral-lunge', 'Lateral Lunge', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('step-up', 'Step-Up', 'quads', array['glutes', 'core']::text[], array['stepup']::text[]),
  ('db-step-up', 'DB Step-Up', 'quads', array['glutes', 'core']::text[], array['dumbbell step up', 'db stepup', 'dumbbell stepup']::text[]),
  ('bb-step-up', 'BB Step-Up', 'quads', array['glutes', 'core']::text[], array['barbell step up', 'bb stepup', 'barbell stepup']::text[]),
  ('lateral-step-up', 'Lateral Step-Up', 'quads', array['glutes', 'core']::text[], array['lateral stepup']::text[]),
  ('deficit-step-up', 'Deficit Step-Up', 'quads', array['glutes', 'core']::text[], array['deficit stepup']::text[]),
  ('pistol-squat', 'Pistol Squat', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('assisted-pistol-squat', 'Assisted Pistol Squat', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('skater-squat', 'Skater Squat', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('cossack-squat', 'Cossack Squat', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('sled-push', 'Sled Push', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('sled-drag', 'Sled Drag', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('nordic-reverse-curl', 'Nordic Reverse Curl', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('spanish-squat', 'Spanish Squat', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('terminal-knee-extension', 'Terminal Knee Extension', 'quads', array['glutes', 'core']::text[], '{}'::text[]),
  ('petersen-step-up', 'Petersen Step-Up', 'quads', array['glutes', 'core']::text[], array['petersen stepup']::text[]),
  ('romanian-deadlift', 'Romanian Deadlift', 'hamstrings', array['glutes', 'back']::text[], array['rdl']::text[]),
  ('db-romanian-deadlift', 'DB Romanian Deadlift', 'hamstrings', array['glutes', 'back']::text[], array['dumbbell romanian deadlift', 'db rdl', 'dumbbell rdl']::text[]),
  ('single-leg-romanian-deadlift', 'Single-Leg Romanian Deadlift', 'hamstrings', array['glutes', 'back']::text[], array['single leg rdl']::text[]),
  ('db-single-leg-romanian-deadlift', 'DB Single-Leg Romanian Deadlift', 'hamstrings', array['glutes', 'back']::text[], array['dumbbell single leg romanian deadlift', 'db single leg rdl', 'dumbbell single leg rdl']::text[]),
  ('stiff-leg-deadlift', 'Stiff-Leg Deadlift', 'hamstrings', array['glutes', 'back']::text[], array['sldl']::text[]),
  ('deficit-romanian-deadlift', 'Deficit Romanian Deadlift', 'hamstrings', array['glutes', 'back']::text[], array['deficit rdl']::text[]),
  ('sm-romanian-deadlift', 'SM Romanian Deadlift', 'hamstrings', array['glutes', 'back']::text[], array['smith romanian deadlift', 'sm rdl', 'smith rdl']::text[]),
  ('trap-bar-romanian-deadlift', 'Trap Bar Romanian Deadlift', 'hamstrings', array['glutes', 'back']::text[], array['trap bar rdl']::text[]),
  ('kb-romanian-deadlift', 'KB Romanian Deadlift', 'hamstrings', array['glutes', 'back']::text[], array['kettlebell romanian deadlift', 'kb rdl', 'kettlebell rdl']::text[]),
  ('snatch-grip-romanian-deadlift', 'Snatch-Grip Romanian Deadlift', 'hamstrings', array['glutes', 'back']::text[], array['snatch grip rdl']::text[]),
  ('good-morning', 'Good Morning', 'hamstrings', array['glutes', 'back']::text[], array['gm']::text[]),
  ('seated-good-morning', 'Seated Good Morning', 'hamstrings', array['glutes', 'back']::text[], array['seated gm']::text[]),
  ('sm-good-morning', 'SM Good Morning', 'hamstrings', array['glutes', 'back']::text[], array['smith good morning', 'sm gm', 'smith gm']::text[]),
  ('safety-bar-good-morning', 'Safety Bar Good Morning', 'hamstrings', array['glutes', 'back']::text[], array['safety bar gm']::text[]),
  ('banded-good-morning', 'Banded Good Morning', 'hamstrings', array['glutes', 'back']::text[], array['banded gm']::text[]),
  ('jefferson-deadlift', 'Jefferson Deadlift', 'hamstrings', array['glutes', 'back']::text[], '{}'::text[]),
  ('lying-leg-curl', 'Lying Leg Curl', 'hamstrings', array['calves', 'glutes']::text[], '{}'::text[]),
  ('seated-leg-curl', 'Seated Leg Curl', 'hamstrings', array['calves', 'glutes']::text[], '{}'::text[]),
  ('standing-leg-curl', 'Standing Leg Curl', 'hamstrings', array['calves', 'glutes']::text[], '{}'::text[]),
  ('single-leg-lying-curl', 'Single-Leg Lying Curl', 'hamstrings', array['calves', 'glutes']::text[], '{}'::text[]),
  ('single-leg-seated-curl', 'Single-Leg Seated Curl', 'hamstrings', array['calves', 'glutes']::text[], '{}'::text[]),
  ('cable-leg-curl', 'Cable Leg Curl', 'hamstrings', array['calves', 'glutes']::text[], '{}'::text[]),
  ('banded-leg-curl', 'Banded Leg Curl', 'hamstrings', array['calves', 'glutes']::text[], '{}'::text[]),
  ('stability-ball-leg-curl', 'Stability Ball Leg Curl', 'hamstrings', array['calves', 'glutes']::text[], '{}'::text[]),
  ('slider-leg-curl', 'Slider Leg Curl', 'hamstrings', array['calves', 'glutes']::text[], '{}'::text[]),
  ('nordic-hamstring-curl', 'Nordic Hamstring Curl', 'hamstrings', array['calves', 'glutes']::text[], '{}'::text[]),
  ('assisted-nordic-curl', 'Assisted Nordic Curl', 'hamstrings', array['calves', 'glutes']::text[], '{}'::text[]),
  ('razor-curl', 'Razor Curl', 'hamstrings', array['calves', 'glutes']::text[], '{}'::text[]),
  ('glute-ham-raise', 'Glute-Ham Raise', 'hamstrings', array['calves', 'glutes']::text[], array['ghr']::text[]),
  ('machine-glute-ham-raise', 'Machine Glute-Ham Raise', 'hamstrings', array['calves', 'glutes']::text[], array['machine ghr']::text[]),
  ('reverse-nordic', 'Reverse Nordic', 'hamstrings', array['calves', 'glutes']::text[], '{}'::text[]),
  ('cable-pull-through', 'Cable Pull-Through', 'hamstrings', array['glutes', 'core']::text[], '{}'::text[]),
  ('band-pull-through', 'Band Pull-Through', 'hamstrings', array['glutes', 'core']::text[], '{}'::text[]),
  ('kb-swing', 'KB Swing', 'hamstrings', array['glutes', 'core']::text[], array['kettlebell swing']::text[]),
  ('american-kb-swing', 'American KB Swing', 'hamstrings', array['glutes', 'core']::text[], array['american kettlebell swing']::text[]),
  ('single-arm-kb-swing', 'Single-Arm KB Swing', 'hamstrings', array['glutes', 'core']::text[], array['single arm kettlebell swing']::text[]),
  ('hip-hinge-drill', 'Hip Hinge Drill', 'hamstrings', array['glutes', 'core']::text[], '{}'::text[]),
  ('45-degree-hip-extension', '45-Degree Hip Extension', 'hamstrings', array['glutes', 'core']::text[], '{}'::text[]),
  ('single-leg-back-extension', 'Single-Leg Back Extension', 'hamstrings', array['glutes', 'core']::text[], '{}'::text[]),
  ('sled-backward-drag', 'Sled Backward Drag', 'hamstrings', array['glutes', 'core']::text[], '{}'::text[]),
  ('hamstring-slider-bridge', 'Hamstring Slider Bridge', 'hamstrings', array['glutes', 'core']::text[], '{}'::text[]),
  ('single-leg-hamstring-bridge', 'Single-Leg Hamstring Bridge', 'hamstrings', array['glutes', 'core']::text[], '{}'::text[]),
  ('long-lever-bridge', 'Long-Lever Bridge', 'hamstrings', array['glutes', 'core']::text[], '{}'::text[]),
  ('kettlebell-deadlift', 'Kettlebell Deadlift', 'hamstrings', array['glutes', 'core']::text[], array['kb deadlift']::text[]),
  ('stiff-leg-db-deadlift', 'Stiff-Leg DB Deadlift', 'hamstrings', array['glutes', 'core']::text[], array['stiff leg dumbbell deadlift']::text[]),
  ('hyperextension-hold', 'Hyperextension Hold', 'hamstrings', array['glutes', 'core']::text[], '{}'::text[]),
  ('bb-hip-thrust', 'BB Hip Thrust', 'glutes', array['hamstrings', 'quads']::text[], array['barbell hip thrust', 'bb thrust', 'barbell thrust']::text[]),
  ('db-hip-thrust', 'DB Hip Thrust', 'glutes', array['hamstrings', 'quads']::text[], array['dumbbell hip thrust', 'db thrust', 'dumbbell thrust']::text[]),
  ('sm-hip-thrust', 'SM Hip Thrust', 'glutes', array['hamstrings', 'quads']::text[], array['smith hip thrust', 'sm thrust', 'smith thrust']::text[]),
  ('machine-hip-thrust', 'Machine Hip Thrust', 'glutes', array['hamstrings', 'quads']::text[], array['machine thrust']::text[]),
  ('single-leg-hip-thrust', 'Single-Leg Hip Thrust', 'glutes', array['hamstrings', 'quads']::text[], array['single leg thrust']::text[]),
  ('banded-hip-thrust', 'Banded Hip Thrust', 'glutes', array['hamstrings', 'quads']::text[], array['banded thrust']::text[]),
  ('paused-hip-thrust', 'Paused Hip Thrust', 'glutes', array['hamstrings', 'quads']::text[], array['paused thrust']::text[]),
  ('feet-elevated-hip-thrust', 'Feet-Elevated Hip Thrust', 'glutes', array['hamstrings', 'quads']::text[], array['feet elevated thrust']::text[]),
  ('b-stance-hip-thrust', 'B-Stance Hip Thrust', 'glutes', array['hamstrings', 'quads']::text[], array['b stance thrust']::text[]),
  ('glute-bridge', 'Glute Bridge', 'glutes', array['hamstrings', 'quads']::text[], '{}'::text[]),
  ('bb-glute-bridge', 'BB Glute Bridge', 'glutes', array['hamstrings', 'quads']::text[], array['barbell glute bridge']::text[]),
  ('single-leg-glute-bridge', 'Single-Leg Glute Bridge', 'glutes', array['hamstrings', 'quads']::text[], '{}'::text[]),
  ('frog-pump', 'Frog Pump', 'glutes', array['hamstrings', 'quads']::text[], '{}'::text[]),
  ('frog-hip-thrust', 'Frog Hip Thrust', 'glutes', array['hamstrings', 'quads']::text[], array['frog thrust']::text[]),
  ('hip-thrust-machine-plate-loaded', 'Hip Thrust Machine (Plate-Loaded)', 'glutes', array['hamstrings', 'quads']::text[], array['thrust machine plate loaded']::text[]),
  ('cable-glute-kickback', 'Cable Glute Kickback', 'glutes', array['hamstrings', 'core']::text[], '{}'::text[]),
  ('machine-glute-kickback', 'Machine Glute Kickback', 'glutes', array['hamstrings', 'core']::text[], '{}'::text[]),
  ('standing-glute-kickback', 'Standing Glute Kickback', 'glutes', array['hamstrings', 'core']::text[], '{}'::text[]),
  ('quadruped-hip-extension', 'Quadruped Hip Extension', 'glutes', array['hamstrings', 'core']::text[], '{}'::text[]),
  ('donkey-kick', 'Donkey Kick', 'glutes', array['hamstrings', 'core']::text[], '{}'::text[]),
  ('fire-hydrant', 'Fire Hydrant', 'glutes', array['hamstrings', 'core']::text[], '{}'::text[]),
  ('banded-kickback', 'Banded Kickback', 'glutes', array['hamstrings', 'core']::text[], '{}'::text[]),
  ('cable-pull-through-glute-focus', 'Cable Pull-Through (Glute Focus)', 'glutes', array['hamstrings', 'core']::text[], '{}'::text[]),
  ('reverse-hyper-glute-focus', 'Reverse Hyper (Glute Focus)', 'glutes', array['hamstrings', 'core']::text[], '{}'::text[]),
  ('kneeling-hip-thrust', 'Kneeling Hip Thrust', 'glutes', array['hamstrings', 'core']::text[], array['kneeling thrust']::text[]),
  ('kneeling-banded-hip-thrust', 'Kneeling Banded Hip Thrust', 'glutes', array['hamstrings', 'core']::text[], array['kneeling banded thrust']::text[]),
  ('single-leg-hip-extension', 'Single-Leg Hip Extension', 'glutes', array['hamstrings', 'core']::text[], '{}'::text[]),
  ('hip-abduction-machine', 'Hip Abduction Machine', 'glutes', array['quads', 'core']::text[], '{}'::text[]),
  ('seated-hip-abduction', 'Seated Hip Abduction', 'glutes', array['quads', 'core']::text[], '{}'::text[]),
  ('standing-cable-abduction', 'Standing Cable Abduction', 'glutes', array['quads', 'core']::text[], '{}'::text[]),
  ('banded-lateral-walk', 'Banded Lateral Walk', 'glutes', array['quads', 'core']::text[], '{}'::text[]),
  ('monster-walk', 'Monster Walk', 'glutes', array['quads', 'core']::text[], '{}'::text[]),
  ('clamshell', 'Clamshell', 'glutes', array['quads', 'core']::text[], '{}'::text[]),
  ('side-lying-hip-raise', 'Side-Lying Hip Raise', 'glutes', array['quads', 'core']::text[], '{}'::text[]),
  ('copenhagen-plank', 'Copenhagen Plank', 'glutes', array['quads', 'core']::text[], '{}'::text[]),
  ('hip-adduction-machine', 'Hip Adduction Machine', 'glutes', array['quads', 'core']::text[], '{}'::text[]),
  ('cable-hip-adduction', 'Cable Hip Adduction', 'glutes', array['quads', 'core']::text[], '{}'::text[]),
  ('sumo-squat', 'Sumo Squat', 'glutes', array['quads', 'core']::text[], '{}'::text[]),
  ('db-sumo-squat', 'DB Sumo Squat', 'glutes', array['quads', 'core']::text[], array['dumbbell sumo squat']::text[]),
  ('kb-sumo-deadlift', 'KB Sumo Deadlift', 'glutes', array['quads', 'core']::text[], array['kettlebell sumo deadlift']::text[]),
  ('curtsy-squat', 'Curtsy Squat', 'glutes', array['quads', 'core']::text[], '{}'::text[]),
  ('step-up-glute-focus', 'Step-Up (Glute Focus)', 'glutes', array['quads', 'core']::text[], array['stepup glute focus']::text[]),
  ('deficit-curtsy-lunge', 'Deficit Curtsy Lunge', 'glutes', array['quads', 'core']::text[], '{}'::text[]),
  ('glute-focused-back-extension', 'Glute-Focused Back Extension', 'glutes', array['quads', 'core']::text[], '{}'::text[]),
  ('single-leg-squat-to-box', 'Single-Leg Squat to Box', 'glutes', array['quads', 'core']::text[], '{}'::text[]),
  ('standing-calf-raise', 'Standing Calf Raise', 'calves', '{}'::text[], '{}'::text[]),
  ('machine-standing-calf-raise', 'Machine Standing Calf Raise', 'calves', '{}'::text[], '{}'::text[]),
  ('sm-calf-raise', 'SM Calf Raise', 'calves', '{}'::text[], array['smith calf raise']::text[]),
  ('bb-standing-calf-raise', 'BB Standing Calf Raise', 'calves', '{}'::text[], array['barbell standing calf raise']::text[]),
  ('db-standing-calf-raise', 'DB Standing Calf Raise', 'calves', '{}'::text[], array['dumbbell standing calf raise']::text[]),
  ('single-leg-standing-calf-raise', 'Single-Leg Standing Calf Raise', 'calves', '{}'::text[], '{}'::text[]),
  ('bodyweight-calf-raise', 'Bodyweight Calf Raise', 'calves', '{}'::text[], '{}'::text[]),
  ('deficit-calf-raise', 'Deficit Calf Raise', 'calves', '{}'::text[], '{}'::text[]),
  ('paused-calf-raise', 'Paused Calf Raise', 'calves', '{}'::text[], '{}'::text[]),
  ('seated-calf-raise', 'Seated Calf Raise', 'calves', '{}'::text[], '{}'::text[]),
  ('machine-seated-calf-raise', 'Machine Seated Calf Raise', 'calves', '{}'::text[], '{}'::text[]),
  ('db-seated-calf-raise', 'DB Seated Calf Raise', 'calves', '{}'::text[], array['dumbbell seated calf raise']::text[]),
  ('plate-seated-calf-raise', 'Plate Seated Calf Raise', 'calves', '{}'::text[], '{}'::text[]),
  ('leg-press-calf-raise', 'Leg Press Calf Raise', 'calves', '{}'::text[], '{}'::text[]),
  ('hack-squat-calf-raise', 'Hack Squat Calf Raise', 'calves', '{}'::text[], '{}'::text[]),
  ('donkey-calf-raise', 'Donkey Calf Raise', 'calves', '{}'::text[], '{}'::text[]),
  ('machine-donkey-calf-raise', 'Machine Donkey Calf Raise', 'calves', '{}'::text[], '{}'::text[]),
  ('single-leg-leg-press-calf-raise', 'Single-Leg Leg Press Calf Raise', 'calves', '{}'::text[], '{}'::text[]),
  ('banded-calf-raise', 'Banded Calf Raise', 'calves', '{}'::text[], '{}'::text[]),
  ('cable-calf-raise', 'Cable Calf Raise', 'calves', '{}'::text[], '{}'::text[]),
  ('bb-seated-calf-raise', 'BB Seated Calf Raise', 'calves', '{}'::text[], array['barbell seated calf raise']::text[]),
  ('sm-seated-calf-raise', 'SM Seated Calf Raise', 'calves', '{}'::text[], array['smith seated calf raise']::text[]),
  ('single-leg-seated-calf-raise', 'Single-Leg Seated Calf Raise', 'calves', '{}'::text[], '{}'::text[]),
  ('bent-knee-calf-raise', 'Bent-Knee Calf Raise', 'calves', '{}'::text[], '{}'::text[]),
  ('straight-leg-calf-raise', 'Straight-Leg Calf Raise', 'calves', '{}'::text[], '{}'::text[]),
  ('explosive-calf-raise', 'Explosive Calf Raise', 'calves', '{}'::text[], '{}'::text[]),
  ('tibialis-raise', 'Tibialis Raise', 'calves', array['core']::text[], '{}'::text[]),
  ('weighted-tibialis-raise', 'Weighted Tibialis Raise', 'calves', array['core']::text[], '{}'::text[]),
  ('banded-tibialis-raise', 'Banded Tibialis Raise', 'calves', array['core']::text[], '{}'::text[]),
  ('toe-walk', 'Toe Walk', 'calves', array['core']::text[], '{}'::text[]),
  ('heel-walk', 'Heel Walk', 'calves', array['core']::text[], '{}'::text[]),
  ('farmer-walk-on-toes', 'Farmer Walk on Toes', 'calves', array['core']::text[], '{}'::text[]),
  ('jump-rope', 'Jump Rope', 'calves', array['core']::text[], '{}'::text[]),
  ('pogo-hop', 'Pogo Hop', 'calves', array['core']::text[], '{}'::text[]),
  ('calf-jump', 'Calf Jump', 'calves', array['core']::text[], '{}'::text[]),
  ('ankle-bounce', 'Ankle Bounce', 'calves', array['core']::text[], '{}'::text[]),
  ('seated-tibialis-raise', 'Seated Tibialis Raise', 'calves', array['core']::text[], '{}'::text[]),
  ('soleus-push-up', 'Soleus Push-Up', 'calves', array['core']::text[], array['soleus pushup']::text[]),
  ('eccentric-calf-drop', 'Eccentric Calf Drop', 'calves', array['core']::text[], '{}'::text[]),
  ('sled-toe-push', 'Sled Toe Push', 'calves', array['core']::text[], '{}'::text[]),
  ('stair-calf-raise', 'Stair Calf Raise', 'calves', array['core']::text[], '{}'::text[]),
  ('plank', 'Plank', 'core', '{}'::text[], '{}'::text[]),
  ('weighted-plank', 'Weighted Plank', 'core', '{}'::text[], '{}'::text[]),
  ('long-lever-plank', 'Long-Lever Plank', 'core', '{}'::text[], '{}'::text[]),
  ('side-plank', 'Side Plank', 'core', '{}'::text[], '{}'::text[]),
  ('weighted-side-plank', 'Weighted Side Plank', 'core', '{}'::text[], '{}'::text[]),
  ('rkc-plank', 'RKC Plank', 'core', '{}'::text[], '{}'::text[]),
  ('body-saw', 'Body Saw', 'core', '{}'::text[], '{}'::text[]),
  ('stir-the-pot', 'Stir the Pot', 'core', '{}'::text[], '{}'::text[]),
  ('ab-wheel-rollout', 'Ab Wheel Rollout', 'core', '{}'::text[], '{}'::text[]),
  ('kneeling-ab-wheel-rollout', 'Kneeling Ab Wheel Rollout', 'core', '{}'::text[], '{}'::text[]),
  ('standing-ab-wheel-rollout', 'Standing Ab Wheel Rollout', 'core', '{}'::text[], '{}'::text[]),
  ('barbell-rollout', 'Barbell Rollout', 'core', '{}'::text[], array['bb rollout']::text[]),
  ('suspension-fallout', 'Suspension Fallout', 'core', '{}'::text[], '{}'::text[]),
  ('hollow-body-hold', 'Hollow Body Hold', 'core', '{}'::text[], '{}'::text[]),
  ('hollow-rock', 'Hollow Rock', 'core', '{}'::text[], '{}'::text[]),
  ('dead-bug', 'Dead Bug', 'core', '{}'::text[], '{}'::text[]),
  ('weighted-dead-bug', 'Weighted Dead Bug', 'core', '{}'::text[], '{}'::text[]),
  ('bird-dog', 'Bird Dog', 'core', '{}'::text[], '{}'::text[]),
  ('hanging-knee-raise', 'Hanging Knee Raise', 'core', array['hamstrings']::text[], '{}'::text[]),
  ('hanging-leg-raise', 'Hanging Leg Raise', 'core', array['hamstrings']::text[], '{}'::text[]),
  ('weighted-hanging-leg-raise', 'Weighted Hanging Leg Raise', 'core', array['hamstrings']::text[], '{}'::text[]),
  ('toes-to-bar', 'Toes-to-Bar', 'core', array['hamstrings']::text[], '{}'::text[]),
  ('captain-chair-knee-raise', 'Captain Chair Knee Raise', 'core', array['hamstrings']::text[], '{}'::text[]),
  ('captain-chair-leg-raise', 'Captain Chair Leg Raise', 'core', array['hamstrings']::text[], '{}'::text[]),
  ('lying-leg-raise', 'Lying Leg Raise', 'core', array['hamstrings']::text[], '{}'::text[]),
  ('lying-knee-raise', 'Lying Knee Raise', 'core', array['hamstrings']::text[], '{}'::text[]),
  ('decline-leg-raise', 'Decline Leg Raise', 'core', array['hamstrings']::text[], '{}'::text[]),
  ('reverse-crunch', 'Reverse Crunch', 'core', array['hamstrings']::text[], '{}'::text[]),
  ('weighted-reverse-crunch', 'Weighted Reverse Crunch', 'core', array['hamstrings']::text[], '{}'::text[]),
  ('dragon-flag', 'Dragon Flag', 'core', array['hamstrings']::text[], '{}'::text[]),
  ('v-up', 'V-Up', 'core', array['hamstrings']::text[], '{}'::text[]),
  ('tuck-up', 'Tuck-Up', 'core', array['hamstrings']::text[], '{}'::text[]),
  ('jackknife', 'Jackknife', 'core', array['hamstrings']::text[], '{}'::text[]),
  ('crunch', 'Crunch', 'core', '{}'::text[], '{}'::text[]),
  ('weighted-crunch', 'Weighted Crunch', 'core', '{}'::text[], '{}'::text[]),
  ('cable-crunch', 'Cable Crunch', 'core', '{}'::text[], '{}'::text[]),
  ('rope-cable-crunch', 'Rope Cable Crunch', 'core', '{}'::text[], '{}'::text[]),
  ('machine-crunch', 'Machine Crunch', 'core', '{}'::text[], '{}'::text[]),
  ('decline-crunch', 'Decline Crunch', 'core', '{}'::text[], '{}'::text[]),
  ('sit-up', 'Sit-Up', 'core', '{}'::text[], array['situp']::text[]),
  ('weighted-sit-up', 'Weighted Sit-Up', 'core', '{}'::text[], array['weighted situp']::text[]),
  ('decline-sit-up', 'Decline Sit-Up', 'core', '{}'::text[], array['decline situp']::text[]),
  ('ghd-sit-up', 'GHD Sit-Up', 'core', '{}'::text[], array['ghd situp']::text[]),
  ('bicycle-crunch', 'Bicycle Crunch', 'core', '{}'::text[], '{}'::text[]),
  ('toe-touch', 'Toe Touch', 'core', '{}'::text[], '{}'::text[]),
  ('flutter-kick', 'Flutter Kick', 'core', '{}'::text[], '{}'::text[]),
  ('scissor-kick', 'Scissor Kick', 'core', '{}'::text[], '{}'::text[]),
  ('pallof-press', 'Pallof Press', 'core', array['glutes', 'shoulders']::text[], '{}'::text[]),
  ('half-kneeling-pallof-press', 'Half-Kneeling Pallof Press', 'core', array['glutes', 'shoulders']::text[], '{}'::text[]),
  ('cable-woodchop', 'Cable Woodchop', 'core', array['glutes', 'shoulders']::text[], '{}'::text[]),
  ('low-to-high-woodchop', 'Low-to-High Woodchop', 'core', array['glutes', 'shoulders']::text[], '{}'::text[]),
  ('high-to-low-woodchop', 'High-to-Low Woodchop', 'core', array['glutes', 'shoulders']::text[], '{}'::text[]),
  ('russian-twist', 'Russian Twist', 'core', array['glutes', 'shoulders']::text[], '{}'::text[]),
  ('weighted-russian-twist', 'Weighted Russian Twist', 'core', array['glutes', 'shoulders']::text[], '{}'::text[]),
  ('landmine-twist', 'Landmine Twist', 'core', array['glutes', 'shoulders']::text[], '{}'::text[]),
  ('landmine-rainbow', 'Landmine Rainbow', 'core', array['glutes', 'shoulders']::text[], '{}'::text[]),
  ('suitcase-hold', 'Suitcase Hold', 'core', array['glutes', 'shoulders']::text[], '{}'::text[]),
  ('side-bend', 'Side Bend', 'core', array['glutes', 'shoulders']::text[], '{}'::text[]),
  ('cable-side-bend', 'Cable Side Bend', 'core', array['glutes', 'shoulders']::text[], '{}'::text[]),
  ('windmill', 'Windmill', 'core', array['glutes', 'shoulders']::text[], '{}'::text[]),
  ('turkish-get-up', 'Turkish Get-Up', 'core', array['glutes', 'shoulders']::text[], '{}'::text[]),
  ('bear-crawl', 'Bear Crawl', 'core', array['glutes', 'shoulders']::text[], '{}'::text[]),
  ('hanging-windshield-wiper', 'Hanging Windshield Wiper', 'core', array['glutes', 'shoulders']::text[], '{}'::text[]),
  ('dead-bug-pallof', 'Dead Bug Pallof', 'core', array['glutes', 'shoulders']::text[], '{}'::text[]),
  ('snatch', 'Snatch', 'olympic', array['quads', 'traps', 'shoulders', 'back']::text[], '{}'::text[]),
  ('power-snatch', 'Power Snatch', 'olympic', array['quads', 'traps', 'shoulders', 'back']::text[], '{}'::text[]),
  ('hang-snatch', 'Hang Snatch', 'olympic', array['quads', 'traps', 'shoulders', 'back']::text[], '{}'::text[]),
  ('hang-power-snatch', 'Hang Power Snatch', 'olympic', array['quads', 'traps', 'shoulders', 'back']::text[], '{}'::text[]),
  ('block-snatch', 'Block Snatch', 'olympic', array['quads', 'traps', 'shoulders', 'back']::text[], '{}'::text[]),
  ('muscle-snatch', 'Muscle Snatch', 'olympic', array['quads', 'traps', 'shoulders', 'back']::text[], '{}'::text[]),
  ('snatch-pull', 'Snatch Pull', 'olympic', array['quads', 'traps', 'shoulders', 'back']::text[], '{}'::text[]),
  ('high-hang-snatch', 'High Hang Snatch', 'olympic', array['quads', 'traps', 'shoulders', 'back']::text[], '{}'::text[]),
  ('snatch-balance', 'Snatch Balance', 'olympic', array['quads', 'traps', 'shoulders', 'back']::text[], '{}'::text[]),
  ('overhead-squat-snatch', 'Overhead Squat (Snatch)', 'olympic', array['quads', 'traps', 'shoulders', 'back']::text[], '{}'::text[]),
  ('snatch-deadlift', 'Snatch Deadlift', 'olympic', array['quads', 'traps', 'shoulders', 'back']::text[], '{}'::text[]),
  ('db-snatch', 'DB Snatch', 'olympic', array['quads', 'traps', 'shoulders', 'back']::text[], array['dumbbell snatch']::text[]),
  ('single-arm-kb-snatch', 'Single-Arm KB Snatch', 'olympic', array['quads', 'traps', 'shoulders', 'back']::text[], array['single arm kettlebell snatch']::text[]),
  ('clean', 'Clean', 'olympic', array['quads', 'traps', 'shoulders']::text[], '{}'::text[]),
  ('power-clean', 'Power Clean', 'olympic', array['quads', 'traps', 'shoulders']::text[], '{}'::text[]),
  ('hang-clean', 'Hang Clean', 'olympic', array['quads', 'traps', 'shoulders']::text[], '{}'::text[]),
  ('hang-power-clean', 'Hang Power Clean', 'olympic', array['quads', 'traps', 'shoulders']::text[], '{}'::text[]),
  ('block-clean', 'Block Clean', 'olympic', array['quads', 'traps', 'shoulders']::text[], '{}'::text[]),
  ('muscle-clean', 'Muscle Clean', 'olympic', array['quads', 'traps', 'shoulders']::text[], '{}'::text[]),
  ('clean-pull', 'Clean Pull', 'olympic', array['quads', 'traps', 'shoulders']::text[], '{}'::text[]),
  ('high-hang-clean', 'High Hang Clean', 'olympic', array['quads', 'traps', 'shoulders']::text[], '{}'::text[]),
  ('clean-deadlift', 'Clean Deadlift', 'olympic', array['quads', 'traps', 'shoulders']::text[], '{}'::text[]),
  ('db-clean', 'DB Clean', 'olympic', array['quads', 'traps', 'shoulders']::text[], array['dumbbell clean']::text[]),
  ('kb-clean', 'KB Clean', 'olympic', array['quads', 'traps', 'shoulders']::text[], array['kettlebell clean']::text[]),
  ('clean-and-jerk', 'Clean and Jerk', 'olympic', array['quads', 'traps', 'shoulders']::text[], '{}'::text[]),
  ('clean-and-press', 'Clean and Press', 'olympic', array['quads', 'traps', 'shoulders']::text[], '{}'::text[]),
  ('squat-clean', 'Squat Clean', 'olympic', array['quads', 'traps', 'shoulders']::text[], '{}'::text[]),
  ('split-jerk', 'Split Jerk', 'olympic', array['shoulders', 'triceps', 'quads']::text[], '{}'::text[]),
  ('power-jerk', 'Power Jerk', 'olympic', array['shoulders', 'triceps', 'quads']::text[], '{}'::text[]),
  ('push-jerk', 'Push Jerk', 'olympic', array['shoulders', 'triceps', 'quads']::text[], '{}'::text[]),
  ('jerk-from-blocks', 'Jerk from Blocks', 'olympic', array['shoulders', 'triceps', 'quads']::text[], '{}'::text[]),
  ('behind-the-neck-jerk', 'Behind-the-Neck Jerk', 'olympic', array['shoulders', 'triceps', 'quads']::text[], '{}'::text[]),
  ('jerk-balance', 'Jerk Balance', 'olympic', array['shoulders', 'triceps', 'quads']::text[], '{}'::text[]),
  ('jerk-dip', 'Jerk Dip', 'olympic', array['shoulders', 'triceps', 'quads']::text[], '{}'::text[]),
  ('thruster', 'Thruster', 'olympic', array['shoulders', 'triceps', 'quads']::text[], '{}'::text[]),
  ('db-thruster', 'DB Thruster', 'olympic', array['shoulders', 'triceps', 'quads']::text[], array['dumbbell thruster']::text[]),
  ('kb-thruster', 'KB Thruster', 'olympic', array['shoulders', 'triceps', 'quads']::text[], array['kettlebell thruster']::text[]),
  ('wall-ball', 'Wall Ball', 'olympic', array['shoulders', 'triceps', 'quads']::text[], '{}'::text[]),
  ('burpee', 'Burpee', 'olympic', array['core', 'quads', 'back']::text[], '{}'::text[]),
  ('burpee-box-jump', 'Burpee Box Jump', 'olympic', array['core', 'quads', 'back']::text[], '{}'::text[]),
  ('devil-press', 'Devil Press', 'olympic', array['core', 'quads', 'back']::text[], '{}'::text[]),
  ('man-maker', 'Man Maker', 'olympic', array['core', 'quads', 'back']::text[], '{}'::text[]),
  ('battle-rope-wave', 'Battle Rope Wave', 'olympic', array['core', 'quads', 'back']::text[], '{}'::text[]),
  ('sledgehammer-swing', 'Sledgehammer Swing', 'olympic', array['core', 'quads', 'back']::text[], '{}'::text[]),
  ('tire-flip', 'Tire Flip', 'olympic', array['core', 'quads', 'back']::text[], '{}'::text[]),
  ('atlas-stone-lift', 'Atlas Stone Lift', 'olympic', array['core', 'quads', 'back']::text[], '{}'::text[]),
  ('sandbag-clean', 'Sandbag Clean', 'olympic', array['core', 'quads', 'back']::text[], '{}'::text[]),
  ('sandbag-carry', 'Sandbag Carry', 'olympic', array['core', 'quads', 'back']::text[], '{}'::text[]),
  ('keg-toss', 'Keg Toss', 'olympic', array['core', 'quads', 'back']::text[], '{}'::text[]),
  ('medicine-ball-slam', 'Medicine Ball Slam', 'olympic', array['core', 'quads', 'back']::text[], '{}'::text[]),
  ('rotational-med-ball-throw', 'Rotational Med Ball Throw', 'olympic', array['core', 'quads', 'back']::text[], '{}'::text[]),
  ('broad-jump', 'Broad Jump', 'olympic', array['core', 'quads', 'back']::text[], '{}'::text[]),
  ('assault-bike-sprint', 'Assault Bike Sprint', 'olympic', array['core', 'quads', 'back']::text[], '{}'::text[]),
  ('rower-sprint', 'Rower Sprint', 'olympic', array['core', 'quads', 'back']::text[], '{}'::text[]),
  ('ski-erg-sprint', 'Ski Erg Sprint', 'olympic', array['core', 'quads', 'back']::text[], '{}'::text[])
on conflict (id) do update set
  name = excluded.name,
  primary_muscle = excluded.primary_muscle,
  secondary_muscles = excluded.secondary_muscles,
  aliases = excluded.aliases,
  is_official = true;
